// web/portal/src/layouts/components/header/UserCenter.tsx
import { Avatar, Button, Dropdown, Modal, Space, Typography, message } from 'antd'
import {
  HomeOutlined,
  LogoutOutlined,
  UserOutlined,
} from '@ant-design/icons'
import type { MenuProps } from 'antd'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

export function UserCenter() {
  const navigate = useNavigate()
  const location = useLocation()
  const token = useAuthStore((s) => s.token)
  const userInfo = useAuthStore((s) => s.userInfo)
  const logout = useAuthStore((s) => s.logout)

  if (!token) {
    return (
      <Button type="primary" onClick={() => navigate('/auth/login')}>
        登录
      </Button>
    )
  }

  const displayName = userInfo?.nickname || userInfo?.account || '用户'
  const avatarSrc = userInfo?.avatar || undefined

  const items: MenuProps['items'] = [
    {
      key: 'userCenter',
      icon: <UserOutlined />,
      label: '个人中心',
    },
    { type: 'divider' },
    {
      key: 'home',
      icon: <HomeOutlined />,
      label: '首页',
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
    },
  ]

  const onClick: MenuProps['onClick'] = ({ key }) => {
    if (key === 'userCenter') {
      navigate('/usercenter')
      return
    }
    if (key === 'home') {
      navigate('/')
      return
    }
    if (key === 'logout') {
      Modal.confirm({
        title: '退出登录',
        content: '确定退出当前账号？',
        okText: '确认',
        cancelText: '取消',
        onOk: async () => {
          await logout(location.pathname)
          message.success('已退出登录')
        },
      })
    }
  }

  return (
    <Dropdown menu={{ items, onClick }} trigger={['click']} placement="bottomRight">
      <Space className="cursor-pointer select-none" size={8}>
        <Avatar src={avatarSrc} icon={<UserOutlined />} />
        <Typography.Text className="hidden md:inline max-w-28 truncate">
          {displayName}
        </Typography.Text>
      </Space>
    </Dropdown>
  )
}

// admin/src/layouts/components/header/UserCenter.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import type { DropdownOption } from 'naive-ui'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { renderIcon } from '@/utils/icon'
import { useAuthStore } from '@/stores'

const router = useRouter()
const authStore = useAuthStore()
const homePath = import.meta.env.VITE_HOME_PATH

const displayName = computed(() => {
  const nickname = String(authStore.userInfo?.nickname ?? '').trim()
  return nickname || '-'
})

const avatar = computed(() => authStore.userInfo?.avatar || undefined)
const avatarImgProps = { referrerPolicy: 'no-referrer' } as any

// 桌面端用户菜单项。首页使用环境配置路径。
const options = computed<DropdownOption[]>(() => [
  {
    label: '个人中心',
    key: 'userCenter',
    icon: renderIcon('icon-park-outline:user'),
  },
  {
    label: '我的反馈',
    key: 'feedback',
    icon: renderIcon('icon-park-outline:message'),
  },
  {
    type: 'divider',
    key: 'divider-1',
  },
  {
    label: '首页',
    key: 'home',
    icon: renderIcon('icon-park-outline:home'),
  },
  {
    label: '退出登录',
    key: 'logout',
    icon: renderIcon('icon-park-outline:logout'),
  },
])

// 根据下拉菜单 key 分发行为；保留弹窗确认可以避免后续接入真实登出时误触。
function handleSelect(key: string | number) {
  if (key === 'userCenter') {
    router.push('/profile')
  }
  if (key === 'feedback') {
    router.push('/feedback')
  }
  if (key === 'home') {
    router.push(homePath)
  }
  if (key === 'logout') {
    window.$dialog.info({
      title: '退出登录',
      content: '确定退出当前账号？',
      positiveText: '确认',
      negativeText: '取消',
      onPositiveClick: async () => {
        await authStore.logout()
        window.$message.success('已退出登录')
      },
    })
  }
}
</script>

<template>
  <n-dropdown
    trigger="click"
    :options="options"
    @select="handleSelect"
  >
    <div class="flex items-center gap-2">
      <n-avatar
        v-if="avatar"
        round
        class="cursor-pointer"
        :src="avatar"
        :img-props="avatarImgProps"
      />
      <n-avatar
        v-else
        round
        class="cursor-pointer"
      >
        <NovaIcon icon="icon-park-outline:user" />
      </n-avatar>
      <span class="hidden md:inline">{{ displayName }}</span>
    </div>
  </n-dropdown>
</template>
