// web/portal/src/pages/auth/forgot-password.tsx
import { useRef, useState } from 'react'
import { Alert, Button, Form, Input, message } from 'antd'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import * as authApi from '@/api/auth'
import { CaptchaInput, type CaptchaInputHandle } from '@/components/common/CaptchaInput'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail } from '@/utils/validate'
import { AuthSplit } from './AuthSplit'

type FormValues = {
  email: string
  password?: string
  confirmPassword?: string
  captcha_id: string
  captcha_value: string
}

export function ForgotPasswordPage() {
  const [form] = Form.useForm<FormValues>()
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef<CaptchaInputHandle>(null)
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const token = params.get('token') || ''
  const isResetMode = Boolean(token)
  const captchaId = Form.useWatch('captcha_id', form) || ''
  const captchaValue = Form.useWatch('captcha_value', form) || ''

  async function sendLink() {
    try {
      await form.validateFields(['email', 'captcha_value'])
    } catch {
      return
    }
    const values = form.getFieldsValue()
    if (!isValidEmail(values.email || '')) {
      message.warning('请输入有效邮箱')
      return
    }
    setLoading(true)
    try {
      await authApi.forgotPassword({
        email: values.email.trim(),
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('密码重置链接已发送')
      await captchaRef.current?.refresh()
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  async function resetPassword() {
    try {
      await form.validateFields()
    } catch {
      return
    }
    const values = form.getFieldsValue()
    if (!isValidEmail(values.email || '')) {
      message.warning('请输入有效邮箱')
      return
    }

    setLoading(true)
    try {
      const encrypted = await encryptPasswords({ password: values.password || '' })
      await authApi.resetPassword({
        email: values.email.trim(),
        token,
        password: encrypted.values.password || '',
        password_key_id: encrypted.password_key_id,
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('密码已重置，请重新登录')
      navigate('/auth/login')
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthSplit
      title={isResetMode ? '重置密码' : '找回密码'}
      subtitle={
        isResetMode ? '使用邮件重置链接设置新密码。' : '向已启用登录的邮箱发送密码重置链接。'
      }
    >
      <Alert
        type="info"
        showIcon
        className="mb-4"
        message={
          isResetMode
            ? '该重置链接在过期前仅可使用一次。'
            : '仅当该邮箱已启用门户登录时，系统才会发送重置链接。'
        }
      />

      <Form
        form={form}
        layout="vertical"
        initialValues={{ captcha_id: '', captcha_value: '' }}
        onFinish={() => {
          void (isResetMode ? resetPassword() : sendLink())
        }}
      >
        <Form.Item
          name="email"
          label="登录邮箱"
          rules={[{ required: true, message: '请输入登录邮箱' }]}
        >
          <Input placeholder="请输入登录邮箱" allowClear />
        </Form.Item>

        {isResetMode ? (
          <>
            <Form.Item
              name="password"
              label="新密码"
              rules={[
                { required: true, message: '请输入新密码' },
                { min: 8, message: '密码至少 8 个字符' },
              ]}
            >
              <Input.Password placeholder="请输入新密码" />
            </Form.Item>
            <Form.Item
              name="confirmPassword"
              label="确认密码"
              dependencies={['password']}
              rules={[
                { required: true, message: '请确认密码' },
                ({ getFieldValue }) => ({
                  validator(_, value) {
                    if (!value || getFieldValue('password') === value) {
                      return Promise.resolve()
                    }
                    return Promise.reject(new Error('两次输入的密码不一致'))
                  },
                }),
              ]}
            >
              <Input.Password placeholder="请再次输入新密码" />
            </Form.Item>
          </>
        ) : null}

        <Form.Item name="captcha_id" hidden>
          <Input />
        </Form.Item>

        <Form.Item
          name="captcha_value"
          label="验证码"
          rules={[{ required: true, message: '请输入验证码' }]}
        >
          <CaptchaInput
            ref={captchaRef}
            captchaId={captchaId}
            captchaValue={captchaValue}
            onCaptchaIdChange={(v) => form.setFieldValue('captcha_id', v)}
            onCaptchaValueChange={(v) => form.setFieldValue('captcha_value', v)}
          />
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" block loading={loading}>
            {isResetMode ? '重置密码' : '发送重置链接'}
          </Button>
        </Form.Item>

        <div className="flex items-center justify-between">
          <Link to="/auth/login">返回登录</Link>
          {isResetMode ? (
            <Button type="link" className="!px-0" onClick={() => void sendLink()}>
              发送新链接
            </Button>
          ) : (
            <Link to="/auth/register">去注册</Link>
          )}
        </div>
      </Form>
    </AuthSplit>
  )
}

// web/admin/src/views/auth/ForgotPassword.vue
<script setup lang="ts">
import type { FormInst, FormItemRule, FormRules } from 'naive-ui'
import { authApi } from '@/api'
import CaptchaInput from '@/components/common/CaptchaInput.vue'
import { isValidEmail } from '@/utils'
import { encryptPasswords } from '@/utils/security'
import { computed, reactive, ref } from 'vue'
import AuthLayout from './AuthLayout.vue'

const route = useRoute()
const router = useRouter()
const formRef = ref<FormInst | null>(null)
const captchaRef = ref<InstanceType<typeof CaptchaInput> | null>(null)
const loading = ref(false)

const form = reactive({
  email: '',
  token: typeof route.query.token === 'string' ? route.query.token : '',
  password: '',
  confirmPassword: '',
  captcha_id: '',
  captcha_value: '',
})

const isResetMode = computed(() => Boolean(form.token))

function validateConfirmPassword(_rule: FormItemRule, value: string) {
  if (!value) {
    return new Error('请确认密码')
  }
  if (value !== form.password) {
    return new Error('两次输入的密码不一致')
  }
  return true
}

function validateRequiredEmail(_rule: FormItemRule, value: string) {
  const text = String(value ?? '').trim()
  if (!text) {
    return new Error('请输入登录邮箱')
  }
  if (!isValidEmail(text)) {
    return new Error('请输入有效邮箱')
  }
  return true
}

const rules = computed<FormRules>(() => ({
  email: [
    {
      validator: validateRequiredEmail,
      trigger: ['input', 'blur'],
    },
  ],
  password: [
    {
      required: isResetMode.value,
      message: '请输入新密码',
      trigger: ['input', 'blur'],
    },
    {
      min: 8,
      message: '密码至少 8 个字符',
      trigger: ['input', 'blur'],
    },
  ],
  confirmPassword: [
    {
      required: isResetMode.value,
      validator: isResetMode.value ? validateConfirmPassword : undefined,
      trigger: ['input', 'blur'],
    },
  ],
  captcha_value: [
    {
      required: true,
      message: '请输入验证码',
      trigger: ['input', 'blur'],
    },
  ],
}))

async function sendLink() {
  if (isResetMode.value) {
    const emailValidation = validateRequiredEmail({} as FormItemRule, form.email)
    if (emailValidation instanceof Error) {
      window.$message.warning(emailValidation.message)
      return
    }
    if (!form.captcha_value.trim()) {
      window.$message.warning('请输入验证码')
      return
    }
  } else {
    try {
      await formRef.value?.validate()
    } catch {
      return
    }
  }
  loading.value = true
  try {
    await authApi.forgotPassword({
      email: form.email.trim(),
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
    })
    window.$message.success('密码重置链接已发送')
    await captchaRef.value?.refresh()
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}

async function resetPassword() {
  try {
    await formRef.value?.validate()
  } catch {
    return
  }
  loading.value = true
  try {
    const encrypted = await encryptPasswords({ password: form.password })
    await authApi.resetPassword({
      email: form.email.trim(),
      token: form.token,
      password: encrypted.values.password,
      password_key_id: encrypted.password_key_id,
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
    })
    window.$message.success('密码已重置，请重新登录')
    router.push('/auth/login')
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <AuthLayout :title="isResetMode ? '重置管理端密码' : '找回管理端密码'" :subtitle="isResetMode ? '使用邮件重置链接设置新密码。' : '向已启用的管理端登录邮箱发送密码重置链接。'">
    <n-alert class="auth-alert" type="info" :bordered="false">
      {{ isResetMode ? '该重置链接在过期前仅可使用一次。' : '仅当该邮箱已启用管理端登录时，系统才会发送重置链接。' }}
    </n-alert>

    <n-form ref="formRef" :model="form" :rules="rules" size="large">
      <n-form-item path="email" :label="'登录邮箱'">
        <n-input v-model:value="form.email"  clearable>
          <template #prefix>
            <NovaIcon icon="icon-park-outline:mail" />
          </template>
        </n-input>
      </n-form-item>

      <template v-if="isResetMode">
        <n-form-item path="password" :label="'新密码'">
          <n-input v-model:value="form.password" type="password" show-password-on="click" />
        </n-form-item>
        <n-form-item path="confirmPassword" :label="'确认密码'">
          <n-input v-model:value="form.confirmPassword" type="password" show-password-on="click" />
        </n-form-item>
      </template>

      <n-form-item path="captcha_value" :label="'验证码'">
        <CaptchaInput
          ref="captchaRef"
          v-model:captcha-id="form.captcha_id"
          v-model:captcha-value="form.captcha_value"
        />
      </n-form-item>

      <n-button
        type="primary"
        size="large"
        block
        :loading="loading"
        @click="isResetMode ? resetPassword() : sendLink()"
      >
        {{ isResetMode ? '重置密码' : '发送重置链接' }}
      </n-button>

      <div class="auth-links">
        <RouterLink to="/auth/login">返回登录</RouterLink>
        <n-button v-if="isResetMode" text type="primary" @click="sendLink">
          发送新链接
        </n-button>
      </div>
    </n-form>
  </AuthLayout>
</template>

<style scoped>
.auth-alert {
  margin-bottom: 22px;
}

.auth-links {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  margin-top: 22px;
  font-size: 14px;
}

.auth-links a {
  color: var(--n-primary-color, #2563eb);
  text-decoration: none;
}
</style>
