// admin/src/layouts/components/header/UserCenter.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import type { DropdownOption } from 'naive-ui'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { renderIcon } from '@/utils/icon'
import { useAuthStore } from '@/stores'

const router = useRouter()
const authStore = useAuthStore()
const homePath = import.meta.env.VITE_HOME_PATH

const displayName = computed(() => {
  const nickname = String(authStore.userInfo?.nickname ?? '').trim()
  return nickname || '-'
})

const avatar = computed(() => authStore.userInfo?.avatar || undefined)
const avatarImgProps = { referrerPolicy: 'no-referrer' } as any

// 桌面端用户菜单项。首页使用环境配置路径。
const options = computed<DropdownOption[]>(() => [
  {
    label: '个人中心',
    key: 'userCenter',
    icon: renderIcon('icon-park-outline:user'),
  },
  {
    label: '我的反馈',
    key: 'feedback',
    icon: renderIcon('icon-park-outline:message'),
  },
  {
    type: 'divider',
    key: 'divider-1',
  },
  {
    label: '首页',
    key: 'home',
    icon: renderIcon('icon-park-outline:home'),
  },
  {
    label: '退出登录',
    key: 'logout',
    icon: renderIcon('icon-park-outline:logout'),
  },
])

// 根据下拉菜单 key 分发行为；保留弹窗确认可以避免后续接入真实登出时误触。
function handleSelect(key: string | number) {
  if (key === 'userCenter') {
    router.push('/profile')
  }
  if (key === 'feedback') {
    router.push('/feedback')
  }
  if (key === 'home') {
    router.push(homePath)
  }
  if (key === 'logout') {
    window.$dialog.info({
      title: '退出登录',
      content: '确定退出当前账号？',
      positiveText: '确认',
      negativeText: '取消',
      onPositiveClick: async () => {
        await authStore.logout()
        window.$message.success('已退出登录')
      },
    })
  }
}
</script>

<template>
  <n-dropdown
    trigger="click"
    :options="options"
    @select="handleSelect"
  >
    <div class="flex items-center gap-2">
      <n-avatar
        v-if="avatar"
        round
        class="cursor-pointer"
        :src="avatar"
        :img-props="avatarImgProps"
      />
      <n-avatar
        v-else
        round
        class="cursor-pointer"
      >
        <NovaIcon icon="icon-park-outline:user" />
      </n-avatar>
      <span class="hidden md:inline">{{ displayName }}</span>
    </div>
  </n-dropdown>
</template>

// portal/src/layouts/components/header/UserCenter.tsx
/** Author: Charlie */

import { useEffect } from 'react'
import { Avatar, Button, Dropdown, Grid, Modal, Space, Typography, message } from 'antd'
import {
  FormOutlined,
  HomeOutlined,
  LogoutOutlined,
  UserOutlined,
} from '@ant-design/icons'
import type { DropdownProps, MenuProps } from 'antd'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/stores/auth'

const { useBreakpoint } = Grid

type Props = {
  compact?: boolean
  placement?: DropdownProps['placement']
}

export function UserCenter({ compact = false, placement = 'bottomRight' }: Props) {
  const navigate = useNavigate()
  const location = useLocation()
  const screens = useBreakpoint()
  const userInfo = useAuthStore((s) => s.userInfo)
  const ensureSession = useAuthStore((s) => s.ensureSession)
  const logout = useAuthStore((s) => s.logout)

  const loggedIn = Boolean(userInfo?.accountId)

  useEffect(() => {
    void ensureSession()
  }, [ensureSession])

  if (!loggedIn) {
    if (compact) {
      return (
        <Button
          type="text"
          icon={<UserOutlined />}
          aria-label="登录"
          onClick={() => navigate('/auth/login')}
        />
      )
    }

    return (
      <Space size={8} align="center">
        <Button onClick={() => navigate('/auth/register')}>注册</Button>
        <Button type="primary" onClick={() => navigate('/auth/login')}>
          登录
        </Button>
      </Space>
    )
  }

  const displayName = userInfo?.nickname || '-'
  const avatarSrc = userInfo?.avatar || undefined
  const showName = !compact && screens.md

  const items: MenuProps['items'] = [
    {
      key: 'profile',
      icon: <HomeOutlined />,
      label: '用户主页',
    },
    {
      key: 'userCenter',
      icon: <UserOutlined />,
      label: '个人中心',
    },
    {
      key: 'feedback',
      icon: <FormOutlined />,
      label: '我的反馈',
    },
    { type: 'divider' },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
    },
  ]

  const onClick: MenuProps['onClick'] = ({ key }) => {
    if (key === 'profile') {
      navigate(`/profile?account_id=${encodeURIComponent(String(userInfo?.accountId || ''))}`)
      return
    }
    if (key === 'userCenter') {
      navigate('/usercenter')
      return
    }
    if (key === 'feedback') {
      navigate('/feedback')
      return
    }
    if (key === 'logout') {
      Modal.confirm({
        title: '退出登录',
        content: '确定退出当前账号？',
        okText: '确认',
        cancelText: '取消',
        onOk: async () => {
          await logout(location.pathname)
          message.success('已退出登录')
        },
      })
    }
  }

  return (
    <Dropdown menu={{ items, onClick }} trigger={['click']} placement={placement}>
      <Button type="text">
        <Space size={8}>
          <Avatar src={avatarSrc} icon={<UserOutlined />} size={compact ? 32 : 'default'} />
          {showName ? (
            <Typography.Text ellipsis style={{ maxWidth: 112 }}>
              {displayName}
            </Typography.Text>
          ) : null}
        </Space>
      </Button>
    </Dropdown>
  )
}
