// web/portal/src/pages/auth/login.tsx
import { useRef, useState } from 'react'
import { Button, Checkbox, Form, Input, Tabs, message } from 'antd'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { CaptchaInput, type CaptchaInputHandle } from '@/components/common/CaptchaInput'
import { useAuthStore } from '@/stores/auth'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail, isValidPhone } from '@/utils/validate'
import { AuthSplit } from './AuthSplit'

type LoginType = 'ACCOUNT' | 'EMAIL' | 'PHONE'

type FormValues = {
  account?: string
  email?: string
  phone?: string
  password: string
  captcha_id: string
  captcha_value: string
  remember: boolean
}

const tabItems = [
  { key: 'ACCOUNT', label: '账号', placeholder: '请输入账号' },
  { key: 'EMAIL', label: '邮箱', placeholder: '请输入登录邮箱' },
  { key: 'PHONE', label: '手机号', placeholder: '请输入登录手机号' },
]

export function LoginPage() {
  const [form] = Form.useForm<FormValues>()
  const [activeType, setActiveType] = useState<LoginType>('ACCOUNT')
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef<CaptchaInputHandle>(null)
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const login = useAuthStore((s) => s.login)
  const captchaId = Form.useWatch('captcha_id', form) || ''
  const captchaValue = Form.useWatch('captcha_value', form) || ''

  async function onFinish(values: FormValues) {
    const identity =
      activeType === 'ACCOUNT'
        ? values.account?.trim()
        : activeType === 'EMAIL'
          ? values.email?.trim()
          : values.phone?.trim()

    if (!identity) {
      message.warning(`请输入${tabItems.find((t) => t.key === activeType)?.label}`)
      return
    }
    if (activeType === 'EMAIL' && !isValidEmail(identity)) {
      message.warning('请输入有效邮箱')
      return
    }
    if (activeType === 'PHONE' && !isValidPhone(identity)) {
      message.warning('请输入有效手机号')
      return
    }

    setLoading(true)
    try {
      const encrypted = await encryptPasswords({ password: values.password })
      const redirect = await login(
        identity,
        encrypted.values.password || '',
        params.get('redirect') || undefined,
        values.remember,
        activeType,
        {
          password_key_id: encrypted.password_key_id,
          captcha_id: values.captcha_id,
          captcha_value: values.captcha_value,
        },
      )
      message.success('登录成功')
      navigate(redirect)
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  const activeField = activeType.toLowerCase() as 'account' | 'email' | 'phone'

  return (
    <AuthSplit title="登录" subtitle="请选择登录身份。">
        <Form
        form={form}
        layout="vertical"
        initialValues={{ remember: true, captcha_id: '', captcha_value: '' }}
        onFinish={onFinish}
      >
        <Tabs
          activeKey={activeType}
          items={tabItems.map((item) => ({ key: item.key, label: item.label }))}
          onChange={(key) => setActiveType(key as LoginType)}
          style={{ marginBottom: 8 }}
        />

        <Form.Item
          name={activeField}
          label={tabItems.find((t) => t.key === activeType)?.label}
          rules={[{ required: true, message: '请填写登录身份' }]}
        >
          <Input
            placeholder={tabItems.find((t) => t.key === activeType)?.placeholder}
            allowClear
          />
        </Form.Item>

        <Form.Item name="password" label="密码" rules={[{ required: true, message: '请输入密码' }]}>
          <Input.Password placeholder="请输入密码" />
        </Form.Item>

        <Form.Item name="captcha_id" hidden>
          <Input />
        </Form.Item>

        <Form.Item
          name="captcha_value"
          label="验证码"
          rules={[{ required: true, message: '请输入验证码' }]}
        >
          <CaptchaInput
            ref={captchaRef}
            captchaId={captchaId}
            captchaValue={captchaValue}
            onCaptchaIdChange={(v) => form.setFieldValue('captcha_id', v)}
            onCaptchaValueChange={(v) => form.setFieldValue('captcha_value', v)}
          />
        </Form.Item>

        <Form.Item>
          <div className="flex items-center justify-between">
            <Form.Item name="remember" valuePropName="checked" noStyle>
              <Checkbox>记住我</Checkbox>
            </Form.Item>
            <Link to="/auth/forgot-password">忘记密码？</Link>
          </div>
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" block loading={loading}>
            登录
          </Button>
        </Form.Item>
      </Form>

      <div className="text-center text-gray-500">
        还没有账号？ <Link to="/auth/register">立即注册</Link>
      </div>
    </AuthSplit>
  )
}

// web/portal-uniapp/src/pages/auth/login.vue
<template>
  <Layout title="登录" back>
    <view class="auth-page">
      <u-card>
        <template #head>
          <CardHead
            title="登录企业门户"
            sub-title="请选择门户登录身份。"
          />
        </template>
        <template #body>
          <u-tabs
            :list="loginTabs"
            :current="activeIndex"
            @change="changeLoginType"
          ></u-tabs>
          <u-form :model="form">
            <u-form-item>
              <view class="form-field">
                <text>{{ currentLogin.label }}</text>
                <u-input
                  v-model="form[activeField]"
                  :placeholder="currentLogin.placeholder"
                  border="surround"
                  clearable
                ></u-input>
              </view>
            </u-form-item>
            <u-form-item>
              <view class="form-field">
                <text>密码</text>
                <u-input
                  v-model="form.password"
                  type="password"
                  placeholder="请输入密码"
                  border="surround"
                ></u-input>
              </view>
            </u-form-item>
            <u-form-item>
              <view class="form-field">
                <text>验证码</text>
                <CaptchaField
                  ref="captchaRef"
                  v-model:captcha-id="form.captcha_id"
                  v-model:captcha-value="form.captcha_value"
                />
              </view>
            </u-form-item>
          </u-form>
        </template>
        <template #foot>
          <u-button
            text="登录"
            type="primary"
            :loading="loading"
            @click="submit"
          ></u-button>
          <u-button
            text="创建账号"
            plain
            @click="openRegister"
          ></u-button>
        </template>
      </u-card>
    </view>
  </Layout>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import Layout from '@/layouts/index.vue'
import CardHead from '@/components/common/CardHead.vue'
import CaptchaField from '@/components/common/CaptchaField.vue'
import { useAuthStore } from '@/stores/auth'
import { useRouteStore } from '@/stores/route'
import { refreshDict } from '@/utils/dict'

type LoginType = 'ACCOUNT' | 'EMAIL' | 'PHONE'

const authStore = useAuthStore()
const routeStore = useRouteStore()
const loading = ref(false)
const activeType = ref<LoginType>('ACCOUNT')
const captchaRef = ref<InstanceType<typeof CaptchaField> | null>(null)

const loginTypes: Array<{
  key: LoginType
  name: string
  label: string
  placeholder: string
}> = [
  {
    key: 'ACCOUNT',
    name: '账号',
    label: '账号',
    placeholder: '请输入账号',
  },
  {
    key: 'EMAIL',
    name: '邮箱',
    label: '邮箱',
    placeholder: '请输入登录邮箱',
  },
  {
    key: 'PHONE',
    name: '手机号',
    label: '手机号',
    placeholder: '请输入登录手机号',
  },
]

const form = reactive({
  account: '',
  email: '',
  phone: '',
  password: '',
  captcha_id: '',
  captcha_value: '',
})

const loginTabs = computed(() =>
  loginTypes.map((item) => ({ name: item.name, key: item.key }))
)
const currentLogin = computed(
  () =>
    loginTypes.find((item) => item.key === activeType.value) || loginTypes[0]
)
const activeField = computed(
  () => activeType.value.toLowerCase() as 'account' | 'email' | 'phone'
)
const activeIndex = computed(() =>
  loginTypes.findIndex((item) => item.key === activeType.value)
)

function changeLoginType(
  event: number | { index?: number; name?: string; key?: LoginType }
) {
  if (typeof event === 'number') {
    activeType.value = loginTypes[event]?.key || 'ACCOUNT'
    return
  }
  if (event.key) {
    activeType.value = event.key
    return
  }
  if (typeof event.index === 'number') {
    activeType.value = loginTypes[event.index]?.key || 'ACCOUNT'
    return
  }
  activeType.value =
    loginTypes.find((item) => item.name === event.name)?.key || 'ACCOUNT'
}

async function submit() {
  const identity = form[activeField.value].trim()
  if (!identity || !form.password || !form.captcha_value) {
    uni.showToast({ title: '请完整填写登录信息', icon: 'none' })
    return
  }
  loading.value = true
  try {
    await authStore.login({
      account: identity,
      password: form.password,
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
      identity_type: activeType.value,
    })
    await Promise.all([refreshDict(), routeStore.initRoutes()])
    uni.switchTab({ url: '/pages/usercenter/index' })
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}

function openRegister() {
  uni.navigateTo({ url: '/pages/auth/register' })
}
</script>

<style lang="scss" scoped>
.auth-page {
  min-height: 100vh;
  display: flex;
  align-items: center;
}

.form-field {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 8rpx;
}
</style>
