// web/admin/src/components/editor/MdPreview.vue
<script setup lang="ts">
import type { Themes } from 'md-editor-v3'
import { MdPreview } from 'md-editor-v3'
import { computed } from 'vue'
import 'md-editor-v3/lib/preview.css'

const props = withDefaults(
  defineProps<{
    value?: string | null
    theme?: Themes
    language?: string
    previewTheme?: string
    codeTheme?: string
    showCodeRowNumber?: boolean
  }>(),
  {
    value: '',
    theme: 'light',
    language: 'zh-CN',
    previewTheme: 'default',
    codeTheme: 'atom',
    showCodeRowNumber: true,
  },
)

const modelValue = computed(() => props.value ?? '')
</script>

<template>
  <div class="editor-preview">
    <MdPreview
      :model-value="modelValue"
      :theme="theme"
      :language="language"
      :preview-theme="previewTheme"
      :code-theme="codeTheme"
      :show-code-row-number="showCodeRowNumber"
    />
  </div>
</template>

<style scoped>
.editor-preview {
  width: 100%;
  min-width: 0;
}
</style>

// web/portal/src/components/editor/MdPreview.tsx
import { MdPreview as MdPreviewBase } from 'md-editor-rt'
import 'md-editor-rt/lib/preview.css'

type Props = {
  value?: string | null
  className?: string
  previewTheme?: string
  codeTheme?: string
  showCodeRowNumber?: boolean
}

export function MdPreview({
  value = '',
  className,
  previewTheme = 'github',
  codeTheme = 'atom',
  showCodeRowNumber = true,
}: Props) {
  return (
    <div className={className}>
      <MdPreviewBase
        value={value ?? ''}
        previewTheme={previewTheme}
        codeTheme={codeTheme}
        showCodeRowNumber={showCodeRowNumber}
        style={{ padding: 0 }}
      />
    </div>
  )
}
