// portal/src/components/editor/CodeEditor.tsx
/** Author: Charlie */

import { memo, useEffect, useRef } from 'react'
import * as monaco from 'monaco-editor'
import { useAppStore } from '@/stores/app'
import { resolveMonacoTheme, type EditorThemeMode } from '@/utils/oj'
import './monacoWorkers'

type Props = {
  value: string
  language?: string
  readOnly?: boolean
  /** auto | vs | vs-dark；默认跟随站点 */
  themeMode?: EditorThemeMode
  onChange?: (value: string) => void
  className?: string
}

export const CodeEditor = memo(function CodeEditor({
  value,
  language = 'plaintext',
  readOnly = false,
  themeMode = 'auto',
  onChange,
  className,
}: Props) {
  const containerRef = useRef<HTMLDivElement | null>(null)
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null)
  const onChangeRef = useRef(onChange)
  const resolvedTheme = useAppStore((s) => s.resolvedTheme)
  const monacoTheme = resolveMonacoTheme(themeMode, resolvedTheme)

  useEffect(() => {
    onChangeRef.current = onChange
  }, [onChange])

  useEffect(() => {
    if (!containerRef.current) {
      return
    }
    const editor = monaco.editor.create(containerRef.current, {
      value,
      language,
      readOnly,
      automaticLayout: true,
      minimap: { enabled: false },
      fontSize: 14,
      scrollBeyondLastLine: false,
      theme: monacoTheme,
      padding: { top: 12 },
    })
    editorRef.current = editor
    const disposable = editor.onDidChangeModelContent(() => {
      onChangeRef.current?.(editor.getValue())
    })
    return () => {
      disposable.dispose()
      editor.dispose()
      editorRef.current = null
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount once
  }, [])

  useEffect(() => {
    const editor = editorRef.current
    if (!editor) {
      return
    }
    if (editor.getValue() !== value) {
      editor.setValue(value)
    }
  }, [value])

  useEffect(() => {
    const editor = editorRef.current
    const model = editor?.getModel()
    if (model) {
      monaco.editor.setModelLanguage(model, language)
    }
  }, [language])

  useEffect(() => {
    monaco.editor.setTheme(monacoTheme)
  }, [monacoTheme])

  useEffect(() => {
    editorRef.current?.updateOptions({ readOnly })
  }, [readOnly])

  return <div ref={containerRef} className={`h-full w-full ${className ?? ''}`} />
})

// web/portal-nuxt/app/components/editor/CodeEditor.vue
<script setup lang="ts">
import type * as monaco from 'monaco-editor'
import { computed, onBeforeUnmount, onMounted, shallowRef, watch } from 'vue'
import './monacoWorkers'

const props = withDefaults(
  defineProps<{
    modelValue?: string | null
    language?: string
    theme?: string
    height?: string | number
    readOnly?: boolean
  }>(),
  {
    modelValue: '',
    language: 'cpp',
    theme: 'vs',
    height: 360,
    readOnly: false,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: string]
}>()

const colorMode = useColorMode()
const containerRef = ref<HTMLElement | null>(null)
const monacoRef = shallowRef<typeof monaco | null>(null)
const editorRef = shallowRef<monaco.editor.IStandaloneCodeEditor | null>(null)
let disposed = false

const containerStyle = computed(() => ({
  height: typeof props.height === 'number' ? `${props.height}px` : props.height,
}))

const resolvedTheme = computed(() => {
  if (props.theme !== 'vs')
    return props.theme
  return colorMode.value === 'dark' ? 'vs-dark' : 'vs'
})

async function loadMonaco() {
  if (!monacoRef.value)
    monacoRef.value = await import('monaco-editor')
  return monacoRef.value
}

onMounted(async () => {
  if (!containerRef.value)
    return
  const monacoInstance = await loadMonaco()
  if (disposed || !containerRef.value)
    return
  editorRef.value = monacoInstance.editor.create(containerRef.value, {
    value: props.modelValue ?? '',
    language: props.language,
    theme: resolvedTheme.value,
    readOnly: props.readOnly,
    automaticLayout: true,
    minimap: { enabled: false },
    scrollBeyondLastLine: false,
    fontSize: 14,
  })
  editorRef.value.onDidChangeModelContent(() => {
    emit('update:modelValue', editorRef.value?.getValue() ?? '')
  })
})

watch(
  () => props.modelValue,
  (value) => {
    const editor = editorRef.value
    if (!editor || editor.getValue() === (value ?? ''))
      return
    editor.setValue(value ?? '')
  },
)

watch(
  () => props.language,
  (language) => {
    const editor = editorRef.value
    const monacoInstance = monacoRef.value
    if (!editor || !monacoInstance)
      return
    const model = editor.getModel()
    if (model)
      monacoInstance.editor.setModelLanguage(model, language)
  },
)

watch(resolvedTheme, (theme) => {
  monacoRef.value?.editor.setTheme(theme)
})

onBeforeUnmount(() => {
  disposed = true
  editorRef.value?.dispose()
  editorRef.value = null
})
</script>

<template>
  <div
    ref="containerRef"
    class="w-full overflow-hidden rounded-lg border border-default"
    :style="containerStyle"
  />
</template>
