// web/portal/src/pages/usercenter/index.tsx
import { useEffect, useState } from 'react'
import {
  Avatar,
  Button,
  Card,
  Col,
  Descriptions,
  Divider,
  Form,
  Input,
  Modal,
  Row,
  Spin,
  Switch,
  Tabs,
  Typography,
  message,
} from 'antd'
import { UserOutlined } from '@ant-design/icons'
import * as authApi from '@/api/auth'
import type { PortalMeResponse, PortalProfileData } from '@/api/auth'
import { useAuthStore } from '@/stores/auth'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail } from '@/utils/validate'
import { AvatarUploadModal } from './components/AvatarUploadModal'

const mapNames = (items?: { id: string; name: string }[]) =>
  (items ?? []).map((item) => item.name).filter(Boolean).join(' / ')

const displayValue = (value: unknown) => (value ? String(value) : '未设置')

type BindConfirmState = {
  show: boolean
  type: 'phone' | 'email'
  password: string
  loading: boolean
}

export function UserCenterPage() {
  const refreshUserInfo = useAuthStore((s) => s.refreshUserInfo)

  const [loading, setLoading] = useState(true)
  const [me, setMe] = useState<PortalMeResponse | null>(null)
  const [avatarModalShow, setAvatarModalShow] = useState(false)

  const [profileForm] = Form.useForm()
  const [passwordForm] = Form.useForm()
  const [phoneForm] = Form.useForm()
  const [emailForm] = Form.useForm()

  const [savingProfile, setSavingProfile] = useState(false)
  const [savingPassword, setSavingPassword] = useState(false)
  const [savingBind, setSavingBind] = useState(false)

  const [bindConfirm, setBindConfirm] = useState<BindConfirmState>({
    show: false,
    type: 'phone',
    password: '',
    loading: false,
  })

  useEffect(() => {
    void loadMe()
  }, [])

  async function loadMe() {
    setLoading(true)
    try {
      await refreshMe()
    } finally {
      setLoading(false)
    }
  }

  async function refreshMe() {
    const data = await refreshUserInfo()
    setMe(data)
    syncForms(data)
  }

  function syncForms(data: PortalMeResponse) {
    const profile = (data.profile ?? {}) as PortalProfileData
    profileForm.setFieldsValue({
      name: data.name ?? profile.name ?? '',
      nickname: data.nickname ?? profile.nickname ?? '',
      signature: profile.signature ?? '',
    })
    phoneForm.setFieldsValue({
      phone: profile.phone ?? '',
      phone_login_enabled: Boolean(profile.phone_login_enabled),
    })
    emailForm.setFieldsValue({
      email: profile.email ?? '',
      email_login_enabled: Boolean(profile.email_login_enabled),
    })
  }

  async function saveProfile() {
    setSavingProfile(true)
    try {
      const values = await profileForm.validateFields()
      await authApi.updateUserCenterProfile({
        name: values.name || null,
        nickname: values.nickname || null,
        signature: values.signature || null,
      })
      await refreshMe()
      message.success('保存成功')
    } finally {
      setSavingProfile(false)
    }
  }

  async function savePassword() {
    const values = await passwordForm.validateFields()
    if (values.new_password !== values.confirm_password) {
      message.warning('两次输入的新密码不一致')
      return
    }
    setSavingPassword(true)
    try {
      const encrypted = await encryptPasswords({
        old_password: values.old_password,
        new_password: values.new_password,
      })
      await authApi.updateUserCenterPassword({
        old_password: encrypted.values.old_password || '',
        new_password: encrypted.values.new_password || '',
        password_key_id: encrypted.password_key_id,
      })
      passwordForm.resetFields()
      message.success('密码已更新')
    } finally {
      setSavingPassword(false)
    }
  }

  async function savePhone() {
    await phoneForm.validateFields()
    openBindConfirm('phone')
  }

  async function saveEmail() {
    const values = await emailForm.validateFields()
    const email = (values.email ?? '').trim()
    if (email && !isValidEmail(email)) {
      message.warning('请输入有效邮箱')
      return
    }
    openBindConfirm('email')
  }

  function openBindConfirm(type: 'phone' | 'email') {
    setBindConfirm({ show: true, type, password: '', loading: false })
  }

  async function confirmBind() {
    if (!bindConfirm.password) {
      message.warning('请输入当前密码')
      return
    }
    setBindConfirm((s) => ({ ...s, loading: true }))
    setSavingBind(true)
    try {
      const encrypted = await encryptPasswords({ password: bindConfirm.password })
      if (bindConfirm.type === 'phone') {
        const values = phoneForm.getFieldsValue()
        await authApi.updateUserCenterPhone({
          password: encrypted.values.password || '',
          password_key_id: encrypted.password_key_id,
          phone: values.phone || null,
          phone_login_enabled: Boolean(values.phone_login_enabled),
        })
      } else {
        const values = emailForm.getFieldsValue()
        await authApi.updateUserCenterEmail({
          password: encrypted.values.password || '',
          password_key_id: encrypted.password_key_id,
          email: (values.email ?? '').trim() || null,
          email_login_enabled: Boolean(values.email_login_enabled),
        })
      }
      setBindConfirm((s) => ({ ...s, show: false, password: '' }))
      await refreshMe()
      message.success('绑定已更新')
    } finally {
      setBindConfirm((s) => ({ ...s, loading: false }))
      setSavingBind(false)
    }
  }

  const profile = (me?.profile ?? {}) as PortalProfileData
  const displayName = me?.nickname || me?.name || '-'
  const avatarUrl = me?.avatar || profile.avatar || undefined
  const roleNames = mapNames(me?.role_id_names)
  const contactParts = [profile.phone, profile.email].filter(Boolean)
  const contactText = contactParts.length ? contactParts.join(' / ') : '未设置'

  const tabItems = [
    {
      key: 'basic_info',
      label: '基本信息',
      children: (
        <Form form={profileForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item label="账号">
            <Input value={me?.account} disabled />
          </Form.Item>
          <Form.Item
            name="name"
            label="姓名"
            rules={[{ max: 64, message: '姓名最多 64 个字符' }]}
          >
            <Input placeholder="请输入姓名" allowClear />
          </Form.Item>
          <Form.Item
            name="nickname"
            label="昵称"
            rules={[{ max: 64, message: '昵称最多 64 个字符' }]}
          >
            <Input placeholder="请输入昵称" allowClear />
          </Form.Item>
          <Form.Item name="signature" label="个性签名">
            <Input.TextArea rows={3} placeholder="介绍一下自己" allowClear />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingProfile} onClick={() => void saveProfile()}>
              保存
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'password',
      label: '密码',
      children: (
        <Form form={passwordForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item
            name="old_password"
            label="旧密码"
            rules={[{ required: true, message: '请输入旧密码' }]}
          >
            <Input.Password placeholder="请输入旧密码" />
          </Form.Item>
          <Form.Item
            name="new_password"
            label="新密码"
            rules={[
              { required: true, message: '请输入新密码' },
              { min: 6, message: '密码至少 6 个字符' },
            ]}
          >
            <Input.Password placeholder="至少 6 个字符" />
          </Form.Item>
          <Form.Item
            name="confirm_password"
            label="确认密码"
            dependencies={['new_password']}
            rules={[
              { required: true, message: '请确认新密码' },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('new_password') === value) {
                    return Promise.resolve()
                  }
                  return Promise.reject(new Error('两次输入的新密码不一致'))
                },
              }),
            ]}
          >
            <Input.Password placeholder="再次输入新密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingPassword} onClick={() => void savePassword()}>
              修改密码
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'phone',
      label: '手机号',
      children: (
        <Form form={phoneForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item name="phone" label="手机号">
            <Input placeholder="请输入手机号" allowClear />
          </Form.Item>
          <Form.Item
            name="phone_login_enabled"
            label="启用手机号登录"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingBind} onClick={() => void savePhone()}>
              修改手机号
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'email',
      label: '邮箱',
      children: (
        <Form form={emailForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item
            name="email"
            label="邮箱"
            rules={[{ type: 'email', message: '邮箱格式不正确' }]}
          >
            <Input placeholder="your@example.com" allowClear />
          </Form.Item>
          <Form.Item
            name="email_login_enabled"
            label="启用邮箱登录"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingBind} onClick={() => void saveEmail()}>
              修改邮箱
            </Button>
          </Form.Item>
        </Form>
      ),
    },
  ]

  return (
    <div className="w-full min-w-0">
      <Spin spinning={loading}>
        <Row gutter={[16, 16]}>
          <Col xs={24} lg={7} className="min-w-0">
            <Card className="h-full" styles={{ body: { minWidth: 0 } }}>
              <div className="flex flex-col items-center text-center">
                <button
                  type="button"
                  className="avatar-trigger"
                  title="更换头像"
                  onClick={() => setAvatarModalShow(true)}
                >
                  <Avatar
                    size={104}
                    src={avatarUrl}
                    icon={<UserOutlined />}
                    style={{ display: 'block' }}
                  />
                </button>
                <div className="mt-4 max-w-full truncate text-xl font-medium">
                  {displayName}
                </div>
                <div className="mt-1 max-w-full truncate text-sm text-gray-500">
                  {me?.account}
                </div>
              </div>

              <Divider />

              <Descriptions column={1} size="small" labelStyle={{ width: 72 }}>
                <Descriptions.Item label="角色">
                  {roleNames || '未设置'}
                </Descriptions.Item>
                <Descriptions.Item label="联系方式">{contactText}</Descriptions.Item>
              </Descriptions>

              <Divider />

              <div className="text-sm font-medium">个性签名</div>
              <div className="mt-2 min-h-16 rounded border border-gray-200 p-3 text-sm text-gray-500">
                {displayValue(profile.signature)}
              </div>
            </Card>
          </Col>

          <Col xs={24} lg={17} className="min-w-0">
            <Card className="w-full min-w-0" styles={{ body: { minWidth: 0 } }}>
              <Tabs items={tabItems} />
            </Card>
          </Col>
        </Row>
      </Spin>

      <Modal
        open={bindConfirm.show}
        title={bindConfirm.type === 'phone' ? '确认更新手机号' : '确认更新邮箱'}
        okText="确认"
        cancelText="取消"
        confirmLoading={bindConfirm.loading}
        maskClosable={false}
        onOk={() => void confirmBind()}
        onCancel={() => setBindConfirm((s) => ({ ...s, show: false }))}
      >
        <Form layout="vertical">
          <Form.Item label="当前密码">
            <Input.Password
              value={bindConfirm.password}
              placeholder="请输入当前密码"
              onChange={(e) => setBindConfirm((s) => ({ ...s, password: e.target.value }))}
              onPressEnter={() => void confirmBind()}
            />
          </Form.Item>
        </Form>
        <Typography.Text type="secondary">
          为保障账号安全，修改{bindConfirm.type === 'phone' ? '手机号' : '邮箱'}需验证当前密码。
        </Typography.Text>
      </Modal>

      <AvatarUploadModal
        open={avatarModalShow}
        avatar={avatarUrl}
        onClose={() => setAvatarModalShow(false)}
        onUploaded={() => void refreshMe()}
      />
    </div>
  )
}

// web/admin/src/views/usercenter/index.vue
<script setup lang="ts">
import type { FormInst, FormItemRule, FormRules } from 'naive-ui'
import { authApi } from '@/api'
import { useAuthStore } from '@/stores'
import { isValidEmail, resolveFileUrl } from '@/utils'
import { encryptPasswords } from '@/utils/security'
import { computed, onMounted, reactive, ref } from 'vue'
import AvatarUploadModal from './components/AvatarUploadModal.vue'

const authStore = useAuthStore()
const emailFormRef = ref<FormInst | null>(null)
const avatarImgProps = { referrerPolicy: 'no-referrer' } as any

const state = reactive({
  loading: false,
  savingProfile: false,
  savingPassword: false,
  savingPhone: false,
  savingEmail: false,
  activeTab: 'basic_info',
  avatarModalShow: false,
  me: null as any,
  profileForm: {
    name: '',
    nickname: '',
    avatar: '',
    signature: '',
    remark: '',
  },
  passwordForm: {
    old_password: '',
    new_password: '',
    confirm_password: '',
  },
  phoneForm: {
    phone: '',
    phone_login_enabled: false,
  },
  emailForm: {
    email: '',
    email_login_enabled: false,
  },
  bindConfirm: {
    show: false,
    type: 'phone' as 'phone' | 'email',
    password: '',
    loading: false,
  },
})

const profile = computed(() => state.me?.profile ?? {})
const avatarUrl = computed(() => resolveFileUrl(state.profileForm.avatar))
const displayName = computed(() => state.me?.nickname || '-')
const roleNames = computed(() => mapNames(state.me?.role_id_names))
const deptNames = computed(() => mapNames(state.me?.dept_id_names))
const mainDept = computed(() => deptNames.value || '未设置')
const mainRole = computed(() => roleNames.value || '未设置')
const contactText = computed(() => {
  const parts = [profile.value.phone, profile.value.email].filter(Boolean)
  return parts.length ? parts.join(' / ') : '未设置'
})
const bindConfirmTitle = computed(() =>
  state.bindConfirm.type === 'phone' ? '确认更新手机号' : '确认更新邮箱',
)
const emailRules = computed<FormRules>(() => ({
  email: [
    {
      validator: validateEmailForm,
      trigger: ['input', 'blur'],
    },
  ],
}))

onMounted(async () => {
  state.loading = true
  try {
    await loadMe()
  } finally {
    state.loading = false
  }
})

async function loadMe() {
  const data = await authStore.refreshUserInfo()
  state.me = data
  syncForms(data)
}

function syncForms(data: any) {
  const currentProfile = data?.profile ?? {}
  state.profileForm.name = data?.name ?? currentProfile.name ?? ''
  state.profileForm.nickname = data?.nickname ?? currentProfile.nickname ?? ''
  state.profileForm.avatar = data?.avatar ?? currentProfile.avatar ?? ''
  state.profileForm.signature = currentProfile.signature ?? ''
  state.profileForm.remark = currentProfile.remark ?? ''
  state.phoneForm.phone = currentProfile.phone ?? ''
  state.emailForm.email = currentProfile.email ?? ''
  state.phoneForm.phone_login_enabled = Boolean(currentProfile.phone_login_enabled)
  state.emailForm.email_login_enabled = Boolean(currentProfile.email_login_enabled)
}

async function saveProfile() {
  state.savingProfile = true
  try {
    await authApi.updateUserCenterProfile({
      name: state.profileForm.name || null,
      nickname: state.profileForm.nickname || null,
      signature: state.profileForm.signature || null,
      remark: state.profileForm.remark || null,
    })
    await refreshMe()
    window.$message.success('保存成功')
  } finally {
    state.savingProfile = false
  }
}

async function savePassword() {
  if (state.passwordForm.new_password !== state.passwordForm.confirm_password) {
    window.$message.warning('两次输入的新密码不一致')
    return
  }
  state.savingPassword = true
  try {
    const encrypted = await encryptPasswords({
      old_password: state.passwordForm.old_password,
      new_password: state.passwordForm.new_password,
    })
    await authApi.updateUserCenterPassword({
      old_password: encrypted.values.old_password,
      new_password: encrypted.values.new_password,
      password_key_id: encrypted.password_key_id,
    })
    state.passwordForm.old_password = ''
    state.passwordForm.new_password = ''
    state.passwordForm.confirm_password = ''
    window.$message.success('密码已更新')
  } finally {
    state.savingPassword = false
  }
}

function savePhone() {
  openBindConfirm('phone')
}

async function saveEmail() {
  try {
    await emailFormRef.value?.validate()
  } catch {
    return
  }
  openBindConfirm('email')
}

function validateEmailForm(_rule: FormItemRule, value: string) {
  const text = String(value ?? '').trim()
  if (!text) {
    return state.emailForm.email_login_enabled ? new Error('请输入邮箱') : true
  }
  if (!isValidEmail(text)) {
    return new Error('请输入有效邮箱')
  }
  return true
}

function openBindConfirm(type: 'phone' | 'email') {
  state.bindConfirm.type = type
  state.bindConfirm.password = ''
  state.bindConfirm.show = true
}

async function confirmBind() {
  if (!state.bindConfirm.password) {
    window.$message.warning('请输入当前密码')
    return
  }
  const isPhone = state.bindConfirm.type === 'phone'
  state.bindConfirm.loading = true
  state.savingPhone = isPhone
  state.savingEmail = !isPhone
  try {
    const encrypted = await encryptPasswords({ password: state.bindConfirm.password })
    if (isPhone) {
      await authApi.updateUserCenterPhone({
        password: encrypted.values.password,
        password_key_id: encrypted.password_key_id,
        phone: state.phoneForm.phone || null,
        phone_login_enabled: state.phoneForm.phone_login_enabled,
      })
    } else {
      await authApi.updateUserCenterEmail({
        password: encrypted.values.password,
        password_key_id: encrypted.password_key_id,
        email: state.emailForm.email.trim() || null,
        email_login_enabled: state.emailForm.email_login_enabled,
      })
    }
    state.bindConfirm.show = false
    state.bindConfirm.password = ''
    await refreshMe()
    window.$message.success('绑定已更新')
  } finally {
    state.bindConfirm.loading = false
    state.savingPhone = false
    state.savingEmail = false
  }
}

async function refreshMe() {
  const data = await authStore.refreshUserInfo()
  state.me = data
  syncForms(data)
}

function mapNames(items?: Array<{ id: string; name: string }>) {
  return (items ?? [])
    .map((item) => item.name)
    .filter(Boolean)
    .join(' / ')
}

function displayValue(value: unknown) {
  return value ? String(value) : '未设置'
}
</script>

<template>
  <div class="w-full min-w-0">
    <NSpin :show="state.loading">
      <NGrid
        class="w-full min-w-0"
        responsive="screen"
        item-responsive
        cols="1 m:24"
        :x-gap="16"
        :y-gap="16"
      >
        <NGridItem span="1 m:7" class="min-w-0">
          <NCard
            :bordered="false"
            class="user-center-profile h-full w-full min-w-0"
            content-class="min-w-0"
            size="small"
          >
            <div class="flex flex-col items-center text-center">
              <button
                class="avatar-trigger"
                type="button"
                :title="'更换头像'"
                @click="state.avatarModalShow = true"
              >
                <NAvatar
                  v-if="avatarUrl"
                  round
                  :size="104"
                  :src="avatarUrl"
                  :img-props="avatarImgProps"
                />
                <NAvatar v-else round :size="104">
                  <NovaIcon icon="icon-park-outline:user" :size="44" />
                </NAvatar>
              </button>
              <div class="mt-4 max-w-full truncate text-xl font-medium">
                {{ displayName }}
              </div>
              <div class="mt-1 max-w-full truncate text-sm text-[var(--text-color-3)]">
                {{ state.me?.account }}
              </div>
            </div>

            <NDivider />

            <NDescriptions :column="1" label-placement="left" size="small">
              <NDescriptionsItem :label="'部门'">
                {{ mainDept }}
              </NDescriptionsItem>
              <NDescriptionsItem :label="'角色'">
                {{ mainRole }}
              </NDescriptionsItem>
              <NDescriptionsItem :label="'联系方式'">
                {{ contactText }}
              </NDescriptionsItem>
            </NDescriptions>

            <NDivider />

            <div class="text-sm font-medium">个性签名</div>
            <div
              class="mt-2 min-h-18 rounded border border-[var(--border-color)] p-3 text-sm text-[var(--text-color-3)]"
            >
              {{ displayValue(profile.signature) }}
            </div>
          </NCard>
        </NGridItem>

        <NGridItem span="1 m:17" class="min-w-0">
          <NCard
            :bordered="false"
            class="w-full min-w-0"
            content-class="min-h-140 min-w-0"
            size="small"
          >
            <NTabs
              v-model:value="state.activeTab"
              type="line"
              animated
              class="user-center-tabs w-full min-w-0"
            >
              <NTabPane name="basic_info" :tab="'基本信息'">
                <NForm class="user-center-form w-full min-w-0" label-placement="top">
                  <NFormItem :label="'账号'">
                    <NInput :value="state.me?.account" disabled />
                  </NFormItem>
                  <NFormItem :label="'姓名'">
                    <NInput v-model:value="state.profileForm.name" />
                  </NFormItem>
                  <NFormItem :label="'昵称'">
                    <NInput v-model:value="state.profileForm.nickname" />
                  </NFormItem>
                  <NFormItem :label="'个性签名'">
                    <NInput v-model:value="state.profileForm.signature" type="textarea" />
                  </NFormItem>
                  <NFormItem :label="'备注'">
                    <NInput v-model:value="state.profileForm.remark" type="textarea" />
                  </NFormItem>
                  <NFormItem :show-label="false">
                    <NButton type="primary" :loading="state.savingProfile" @click="saveProfile">
                      保存
                    </NButton>
                  </NFormItem>
                </NForm>
              </NTabPane>

              <NTabPane name="password" :tab="'密码'">
                <NForm class="user-center-form w-full min-w-0" label-placement="top">
                  <NFormItem :label="'旧密码'">
                    <NInput
                      v-model:value="state.passwordForm.old_password"
                      type="password"
                      show-password-on="click"
                    />
                  </NFormItem>
                  <NFormItem :label="'新密码'">
                    <NInput
                      v-model:value="state.passwordForm.new_password"
                      type="password"
                      show-password-on="click"
                    />
                  </NFormItem>
                  <NFormItem :label="'确认密码'">
                    <NInput
                      v-model:value="state.passwordForm.confirm_password"
                      type="password"
                      show-password-on="click"
                    />
                  </NFormItem>
                  <NFormItem :show-label="false">
                    <NButton type="primary" :loading="state.savingPassword" @click="savePassword">
                      修改密码
                    </NButton>
                  </NFormItem>
                </NForm>
              </NTabPane>

              <NTabPane name="phone" :tab="'手机号'">
                <NForm class="user-center-form w-full min-w-0" label-placement="top">
                  <NFormItem :label="'手机号'">
                    <NInput v-model:value="state.phoneForm.phone" />
                  </NFormItem>
                  <NFormItem :label="'启用手机号登录'">
                    <NSwitch v-model:value="state.phoneForm.phone_login_enabled" />
                  </NFormItem>
                  <NFormItem :show-label="false">
                    <NButton type="primary" :loading="state.savingPhone" @click="savePhone">
                      修改手机号
                    </NButton>
                  </NFormItem>
                </NForm>
              </NTabPane>

              <NTabPane name="email" :tab="'邮箱'">
                <NForm
                  ref="emailFormRef"
                  class="user-center-form w-full min-w-0"
                  :model="state.emailForm"
                  :rules="emailRules"
                  label-placement="top"
                >
                  <NFormItem :label="'邮箱'" path="email">
                    <NInput v-model:value="state.emailForm.email" />
                  </NFormItem>
                  <NFormItem :label="'启用邮箱登录'">
                    <NSwitch v-model:value="state.emailForm.email_login_enabled" />
                  </NFormItem>
                  <NFormItem :show-label="false">
                    <NButton type="primary" :loading="state.savingEmail" @click="saveEmail">
                      修改邮箱
                    </NButton>
                  </NFormItem>
                </NForm>
              </NTabPane>
            </NTabs>
          </NCard>
        </NGridItem>
      </NGrid>
    </NSpin>

    <NModal
      v-model:show="state.bindConfirm.show"
      preset="card"
      :title="bindConfirmTitle"
      class="max-w-120"
      :bordered="false"
      :mask-closable="false"
    >
      <NForm label-placement="top">
        <NFormItem :label="'当前密码'">
          <NInput
            v-model:value="state.bindConfirm.password"
            type="password"
            show-password-on="click"
            :placeholder="'请输入当前密码'"
            @keydown.enter="confirmBind"
          />
        </NFormItem>
      </NForm>
      <template #footer>
        <NSpace justify="end">
          <NButton @click="state.bindConfirm.show = false"> 取消 </NButton>
          <NButton type="primary" :loading="state.bindConfirm.loading" @click="confirmBind">
            确认
          </NButton>
        </NSpace>
      </template>
    </NModal>

    <AvatarUploadModal
      v-model:show="state.avatarModalShow"
      :avatar="avatarUrl"
      @uploaded="refreshMe"
    />
  </div>
</template>

<style scoped>
.user-center-tabs {
  min-width: 0;
}

.user-center-tabs :deep(.n-tabs-nav-scroll-content) {
  -webkit-overflow-scrolling: touch;
  touch-action: pan-x;
}

.user-center-form {
  min-width: 0;
}

.user-center-form :deep(.n-form-item) {
  min-width: 0;
}

.user-center-form :deep(.n-input) {
  width: 100%;
  min-width: min(180px, 100%);
}

.avatar-trigger {
  border: 0;
  border-radius: 999px;
  background: transparent;
  padding: 0;
  cursor: pointer;
  line-height: 0;
  transition:
    background-color 0.2s ease,
    box-shadow 0.2s ease,
    transform 0.2s ease;
}

.avatar-trigger:hover,
.avatar-trigger:focus-visible {
  background: var(--hover-color);
  box-shadow:
    0 0 0 3px var(--card-color),
    0 0 0 5px var(--primary-color-hover);
  transform: translateY(-1px);
  outline: none;
}

.user-center-profile :deep(.n-descriptions-table) {
  width: 100%;
  table-layout: fixed;
}

.user-center-profile :deep(.n-descriptions-table-content) {
  overflow-wrap: anywhere;
}
</style>
