// web/portal-old/src/layouts/components/header/UserCenter.vue
<script setup lang="ts">
import type { DropdownOption } from 'naive-ui'
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { renderIcon } from '@/utils/icon'
import { resolveFileUrl } from '@/utils'
import { useAuthStore } from '@/stores'

const router = useRouter()
const authStore = useAuthStore()
const displayName = computed(() => authStore.userInfo?.nickname || '-')

const avatar = computed(() => resolveFileUrl(authStore.userInfo?.avatar))
const avatarImgProps = { referrerPolicy: 'no-referrer' } as any

const options = computed<DropdownOption[]>(() => [
  {
    label: '个人中心',
    key: 'userCenter',
    icon: renderIcon('icon-park-outline:user'),
  },
  {
    label: '我的空间',
    key: 'mySpace',
    icon: renderIcon('icon-park-outline:user-positioning'),
  },
  {
    type: 'divider',
    key: 'divider-1',
  },
  {
    label: '退出登录',
    key: 'logout',
    icon: renderIcon('icon-park-outline:logout'),
  },
])

function handleSelect(key: string | number) {
  if (key === 'userCenter') {
    router.push({ name: 'usercenter' })
  }
  if (key === 'mySpace') {
    router.push({ name: 'my-space' })
  }
  if (key === 'logout') {
    window.$dialog.info({
      title: '退出登录',
      content: '确定退出当前账号？',
      positiveText: '确认',
      negativeText: '取消',
      onPositiveClick: async () => {
        await authStore.logout()
        window.$message.success('已退出登录')
      },
    })
  }
}
</script>

<template>
  <n-dropdown trigger="click" :options="options" @select="handleSelect">
    <button
      class="min-w-0 inline-flex items-center gap-2 border-0 bg-transparent p-1 text-[var(--text-color-base)] cursor-pointer"
      type="button"
    >
      <n-avatar v-if="avatar" round :size="32" :src="avatar" :img-props="avatarImgProps" />
      <n-avatar v-else round :size="32">
        <NovaIcon icon="icon-park-outline:user" />
      </n-avatar>
      <span class="hidden max-w-28 truncate text-sm font-medium lg:inline">
        {{ displayName }}
      </span>
    </button>
  </n-dropdown>
</template>

// web/portal/src/layouts/components/header/UserCenter.tsx
import { Avatar, Button, Dropdown, Modal, Space, Typography, message } from 'antd'
import {
  HomeOutlined,
  LogoutOutlined,
  UserOutlined,
} from '@ant-design/icons'
import type { MenuProps } from 'antd'
import { useLocation, useNavigate } from 'react-router-dom'
import { resolveFileUrl } from '@/utils/file'
import { useAuthStore } from '@/stores/auth'

export function UserCenter() {
  const navigate = useNavigate()
  const location = useLocation()
  const token = useAuthStore((s) => s.token)
  const userInfo = useAuthStore((s) => s.userInfo)
  const logout = useAuthStore((s) => s.logout)

  if (!token) {
    return (
      <Space size={8}>
        <Button onClick={() => navigate('/auth/register')}>注册</Button>
        <Button type="primary" onClick={() => navigate('/auth/login')}>
          登录
        </Button>
      </Space>
    )
  }

  const displayName = userInfo?.nickname || userInfo?.account || '用户'
  const avatarSrc = resolveFileUrl(userInfo?.avatar)

  const items: MenuProps['items'] = [
    {
      key: 'userCenter',
      icon: <UserOutlined />,
      label: '个人中心',
    },
    { type: 'divider' },
    {
      key: 'home',
      icon: <HomeOutlined />,
      label: '首页',
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
    },
  ]

  const onClick: MenuProps['onClick'] = ({ key }) => {
    if (key === 'userCenter') {
      navigate('/usercenter')
      return
    }
    if (key === 'home') {
      navigate('/')
      return
    }
    if (key === 'logout') {
      Modal.confirm({
        title: '退出登录',
        content: '确定退出当前账号？',
        okText: '确认',
        cancelText: '取消',
        onOk: async () => {
          await logout(location.pathname)
          message.success('已退出登录')
        },
      })
    }
  }

  return (
    <Dropdown menu={{ items, onClick }} trigger={['click']} placement="bottomRight">
      <Space className="cursor-pointer select-none" size={8}>
        <Avatar src={avatarSrc} icon={<UserOutlined />} />
        <Typography.Text className="hidden md:inline max-w-28 truncate">
          {displayName}
        </Typography.Text>
      </Space>
    </Dropdown>
  )
}
