// web/portal/src/pages/contests/index.tsx
import { useEffect, useState } from 'react'
import { Card, Empty, Input, Pagination, Spin, Tag, Typography } from 'antd'
import { Link, useSearchParams } from 'react-router-dom'
import { contestPage } from '@/api/contest'
import type { PortalContestBrief } from '@/api/contest'
import { ContestStatusBadge } from '@/components/oj/ContestStatusBadge'

const formatTime = (value: string | null) => (value ? new Date(value).toLocaleString() : '-')

export function ContestListPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const keyword = searchParams.get('keyword') ?? ''
  const current = Number(searchParams.get('current') ?? 1)
  const size = Number(searchParams.get('size') ?? 12)

  const [loading, setLoading] = useState(true)
  const [data, setData] = useState<PortalContestBrief[]>([])
  const [total, setTotal] = useState(0)
  const [searchText, setSearchText] = useState(keyword)

  async function load() {
    try {
      const res = await contestPage({ current, size, keyword: keyword || undefined })
      setData(res.data.records)
      setTotal(res.data.total)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void load()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [keyword, current, size])

  function onSearch() {
    setLoading(true)
    setSearchParams(searchText ? { keyword: searchText } : {})
  }

  return (
    <div className="space-y-4">
      <Card size="small">
        <div className="flex items-center gap-2">
          <Typography.Title level={4} className="!mb-0">
            竞赛
          </Typography.Title>
          <div className="flex-1" />
          <Input.Search
            className="w-64"
            placeholder="搜索竞赛名称 / 关键字"
            allowClear
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            onSearch={onSearch}
          />
        </div>
      </Card>

      <Spin spinning={loading}>
        {data.length === 0 ? (
          <Card>
            <Empty description="暂无竞赛" />
          </Card>
        ) : (
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {data.map((contest) => (
              <Link key={contest.id} to={`/contests/${contest.id}`} className="block no-underline">
                <Card hoverable className="h-full">
                  <div className="flex items-center justify-between gap-2">
                    <Typography.Text strong className="truncate">
                      {contest.name}
                    </Typography.Text>
                    <ContestStatusBadge status={contest.lifecycle_status} />
                  </div>
                  <div className="mt-2 text-sm text-gray-500">{contest.summary || '暂无简介'}</div>
                  <div className="mt-4 space-y-1 text-xs text-gray-500">
                    <div>
                      时间：{formatTime(contest.start_time)} ~ {formatTime(contest.end_time)}
                    </div>
                    <div>
                      赛制：{contest.format_name}
                      {contest.is_rated ? <Tag className="ml-2">Rated</Tag> : null}
                      {contest.is_private ? <Tag color="orange" className="ml-1">私有</Tag> : null}
                    </div>
                    <div>报名人数：{contest.user_count}</div>
                  </div>
                </Card>
              </Link>
            ))}
          </div>
        )}
      </Spin>

      {total > 0 ? (
        <div className="flex justify-end">
          <Pagination
            current={current}
            pageSize={size}
            total={total}
            showSizeChanger
            showTotal={(t) => `共 ${t} 场`}
            onChange={(nextCurrent, nextSize) => {
              setLoading(true)
              setSearchParams({
                keyword,
                current: String(nextCurrent),
                size: String(nextSize),
              })
            }}
          />
        </div>
      ) : null}
    </div>
  )
}

// web/portal-nuxt/app/pages/contests/index.vue
<script setup lang="ts">
import { fetchContestPage, type PortalContestBrief } from '~/api/biz/contest'
import { format } from 'date-fns'

const keyword = ref('')
const current = ref(1)
const size = ref(20)
const total = ref(0)
const loading = ref(false)
const records = ref<PortalContestBrief[]>([])

async function load() {
  loading.value = true
  try {
    const page = await fetchContestPage({
      current: current.value,
      size: size.value,
      keyword: keyword.value || undefined,
    })
    records.value = page?.records ?? []
    total.value = page?.total ?? 0
  }
  catch {
    records.value = []
    total.value = 0
  }
  finally {
    loading.value = false
  }
}

onMounted(() => load())
watch([current, size], () => {
  if (import.meta.client)
    load()
})

function onSearch() {
  current.value = 1
  load()
}

function fmt(t: string) {
  try {
    return format(new Date(t), 'yyyy-MM-dd HH:mm')
  }
  catch {
    return t
  }
}
</script>

<template>
  <UContainer class="py-8 space-y-6">
    <div class="flex flex-wrap items-end justify-between gap-4">
      <div>
        <h1 class="text-2xl font-semibold">
          竞赛
        </h1>
        <p class="text-muted text-sm mt-1">
          公开竞赛列表
        </p>
      </div>
      <div class="flex gap-2">
        <UInput
          v-model="keyword"
          icon="i-lucide-search"
          placeholder="搜索竞赛"
          class="w-64"
          @keyup.enter="onSearch"
        />
        <UButton @click="onSearch">
          搜索
        </UButton>
      </div>
    </div>

    <div v-if="loading" class="text-muted text-sm">
      加载中…
    </div>
    <div v-else class="space-y-3">
      <NuxtLink
        v-for="c in records"
        :key="c.id"
        :to="`/contests/${c.id}`"
        class="block rounded-xl border border-default px-5 py-4 transition hover:bg-elevated"
      >
        <div class="flex flex-wrap items-center justify-between gap-3">
          <div class="space-y-1">
            <div class="flex items-center gap-2">
              <span class="font-semibold text-lg">{{ c.name }}</span>
              <ContestStatusBadge :status="c.lifecycle_status" />
              <UBadge v-if="c.is_rated" color="primary" variant="subtle">
                Rated
              </UBadge>
            </div>
            <p class="text-sm text-muted">
              {{ c.key }} · {{ c.format_name }} · {{ c.user_count }} 人报名
            </p>
            <p class="text-sm text-muted">
              {{ fmt(c.start_time) }} — {{ fmt(c.end_time) }}
            </p>
          </div>
          <UIcon name="i-lucide-chevron-right" class="size-5 text-muted" />
        </div>
      </NuxtLink>
      <p v-if="!records.length" class="text-muted text-sm">
        暂无竞赛
      </p>
    </div>

    <div class="flex justify-end">
      <UPagination v-model:page="current" :items-per-page="size" :total="total" />
    </div>
  </UContainer>
</template>
