// web/portal/src/pages/auth/register.tsx
import { useRef, useState } from 'react'
import { Button, Form, Input, message } from 'antd'
import { Link, useNavigate } from 'react-router-dom'
import * as authApi from '@/api/auth'
import { CaptchaInput, type CaptchaInputHandle } from '@/components/common/CaptchaInput'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail } from '@/utils/validate'
import { AuthSplit } from './AuthSplit'

type FormValues = {
  account: string
  nickname: string
  email: string
  password: string
  confirmPassword: string
  captcha_id: string
  captcha_value: string
}

export function RegisterPage() {
  const [form] = Form.useForm<FormValues>()
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef<CaptchaInputHandle>(null)
  const navigate = useNavigate()
  const captchaId = Form.useWatch('captcha_id', form) || ''
  const captchaValue = Form.useWatch('captcha_value', form) || ''

  async function onFinish(values: FormValues) {
    const account = values.account.trim()
    const nickname = values.nickname.trim()
    const email = values.email.trim()

    if (account.length < 3 || account.length > 64) {
      message.warning('用户名需 3-64 个字符')
      return
    }
    if (!nickname || nickname.length > 64) {
      message.warning('昵称为必填项')
      return
    }
    if (!isValidEmail(email) || email.length > 128) {
      message.warning('邮箱格式不正确')
      return
    }

    setLoading(true)
    try {
      const encrypted = await encryptPasswords({ password: values.password })
      await authApi.register({
        account,
        email,
        nickname,
        password: encrypted.values.password || '',
        password_key_id: encrypted.password_key_id,
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('注册成功，请登录')
      navigate('/auth/login')
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthSplit title="注册" subtitle="创建门户账号，开始刷题与参赛。">
      <Form
        form={form}
        layout="vertical"
        initialValues={{ captcha_id: '', captcha_value: '' }}
        onFinish={onFinish}
      >
        <Form.Item
          name="account"
          label="用户名"
          rules={[
            { required: true, message: '请输入用户名' },
            { min: 3, max: 64, message: '用户名需 3-64 个字符' },
          ]}
        >
          <Input placeholder="输入用户名" allowClear />
        </Form.Item>

        <Form.Item
          name="nickname"
          label="昵称"
          rules={[
            { required: true, message: '请输入昵称' },
            { max: 64, message: '昵称最多 64 个字符' },
          ]}
        >
          <Input placeholder="输入昵称" allowClear />
        </Form.Item>

        <Form.Item
          name="email"
          label="邮箱"
          rules={[
            { required: true, message: '请输入邮箱' },
            { type: 'email', message: '邮箱格式不正确' },
            { max: 128, message: '邮箱最多 128 个字符' },
          ]}
        >
          <Input placeholder="your@example.com" allowClear />
        </Form.Item>

        <Form.Item
          name="password"
          label="密码"
          rules={[
            { required: true, message: '请输入密码' },
            { min: 6, message: '密码至少 6 个字符' },
          ]}
        >
          <Input.Password placeholder="至少 6 个字符" />
        </Form.Item>

        <Form.Item
          name="confirmPassword"
          label="确认密码"
          dependencies={['password']}
          rules={[
            { required: true, message: '请确认密码' },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue('password') === value) {
                  return Promise.resolve()
                }
                return Promise.reject(new Error('两次密码输入不一致'))
              },
            }),
          ]}
        >
          <Input.Password placeholder="再次输入密码" />
        </Form.Item>

        <Form.Item name="captcha_id" hidden>
          <Input />
        </Form.Item>

        <Form.Item
          name="captcha_value"
          label="验证码"
          rules={[{ required: true, message: '请输入验证码' }]}
        >
          <CaptchaInput
            ref={captchaRef}
            captchaId={captchaId}
            captchaValue={captchaValue}
            onCaptchaIdChange={(v) => form.setFieldValue('captcha_id', v)}
            onCaptchaValueChange={(v) => form.setFieldValue('captcha_value', v)}
          />
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" block loading={loading}>
            注册
          </Button>
        </Form.Item>
      </Form>

      <div className="text-center text-gray-500">
        已有账号？ <Link to="/auth/login">立即登录</Link>
      </div>
    </AuthSplit>
  )
}

// web/portal/src/views/auth/Register.vue
<script setup lang="ts">
import type { FormInst, FormItemRule, FormRules } from 'naive-ui'
import { authApi } from '@/api'
import CaptchaInput from '@/components/common/CaptchaInput.vue'
import { isValidEmail } from '@/utils'
import { encryptPasswords } from '@/utils/security'
import { computed, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import AuthLayout from './AuthLayout.vue'

const router = useRouter()
const formRef = ref<FormInst | null>(null)
const captchaRef = ref<InstanceType<typeof CaptchaInput> | null>(null)
const loading = ref(false)

const form = reactive({
  account: '',
  nickname: '',
  email: '',
  password: '',
  confirmPassword: '',
  captcha_id: '',
  captcha_value: '',
})

function validateConfirmPassword(_rule: FormItemRule, value: string) {
  if (!value) {
    return new Error('Please confirm password')
  }
  if (value !== form.password) {
    return new Error('The two passwords do not match')
  }
  return true
}

function validateRequiredEmail(_rule: FormItemRule, value: string) {
  const text = String(value ?? '').trim()
  if (!text) {
    return new Error('Please enter email')
  }
  if (!isValidEmail(text)) {
    return new Error('Please enter a valid email')
  }
  return true
}

const rules = computed<FormRules>(() => ({
  account: [
    {
      required: true,
      message: 'Please enter account',
      trigger: ['input', 'blur'],
    },
  ],
  nickname: [
    {
      required: true,
      message: 'Please enter nickname',
      trigger: ['input', 'blur'],
    },
  ],
  email: [
    {
      validator: validateRequiredEmail,
      trigger: ['input', 'blur'],
    },
  ],
  password: [
    {
      required: true,
      message: 'Please enter password',
      trigger: ['input', 'blur'],
    },
    {
      min: 8,
      message: 'Password must be at least 8 characters',
      trigger: ['input', 'blur'],
    },
  ],
  confirmPassword: [
    {
      required: true,
      validator: validateConfirmPassword,
      trigger: ['input', 'blur'],
    },
  ],
  captcha_value: [
    {
      required: true,
      message: 'Please enter captcha',
      trigger: ['input', 'blur'],
    },
  ],
}))

async function handleSubmit() {
  try {
    await formRef.value?.validate()
  } catch {
    return
  }

  loading.value = true
  try {
    const encrypted = await encryptPasswords({ password: form.password })
    await authApi.register({
      account: form.account.trim(),
      nickname: form.nickname.trim(),
      email: form.email.trim(),
      password: encrypted.values.password,
      password_key_id: encrypted.password_key_id,
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
    })
    window.$message.success('Registered. Please sign in')
    router.push('/auth/login')
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <AuthLayout :title="'Create Portal Account'" :subtitle="'Create an account with email login enabled by default.'">
    <n-form ref="formRef" :model="form" :rules="rules" size="large" @submit.prevent="handleSubmit">
      <n-form-item path="account" :label="'Account'">
        <n-input v-model:value="form.account" :placeholder="'Enter account'" clearable>
          <template #prefix>
            <NovaIcon icon="icon-park-outline:user" />
          </template>
        </n-input>
      </n-form-item>

      <n-form-item path="nickname" :label="'Nickname'">
        <n-input v-model:value="form.nickname" :placeholder="'Enter nickname'" clearable>
          <template #prefix>
            <NovaIcon icon="icon-park-outline:people" />
          </template>
        </n-input>
      </n-form-item>

      <n-form-item path="email" :label="'Email'">
        <n-input v-model:value="form.email" :placeholder="'Enter email'" clearable>
          <template #prefix>
            <NovaIcon icon="icon-park-outline:mail" />
          </template>
        </n-input>
      </n-form-item>

      <n-form-item path="password" :label="'Password'">
        <n-input
          v-model:value="form.password"
          type="password"
          show-password-on="click"
          :placeholder="'At least 8 characters'"
        >
          <template #prefix>
            <NovaIcon icon="icon-park-outline:lock" />
          </template>
        </n-input>
      </n-form-item>

      <n-form-item path="confirmPassword" :label="'Confirm Password'">
        <n-input
          v-model:value="form.confirmPassword"
          type="password"
          show-password-on="click"
          :placeholder="'Enter password again'"
        >
          <template #prefix>
            <NovaIcon icon="icon-park-outline:check-correct" />
          </template>
        </n-input>
      </n-form-item>

      <n-form-item path="captcha_value" :label="'Captcha'">
        <CaptchaInput
          ref="captchaRef"
          v-model:captcha-id="form.captcha_id"
          v-model:captcha-value="form.captcha_value"
        />
      </n-form-item>

      <n-button
        class="auth-submit"
        type="primary"
        size="large"
        block
        attr-type="submit"
        :loading="loading"
      >
        {{ 'Register' }}
      </n-button>

      <p class="auth-switch">
        {{ 'Already have an account?' }}
        <RouterLink to="/auth/login">{{ 'Back to sign in' }}</RouterLink>
      </p>
    </n-form>
  </AuthLayout>
</template>

<style scoped>
.auth-submit {
  margin-top: 2px;
}

.auth-switch {
  margin-top: 22px;
  font-size: 14px;
  text-align: center;
  color: var(--n-text-color-2);
}

.auth-switch a {
  color: var(--n-primary-color, #2563eb);
  text-decoration: none;
}
</style>
