// web/portal/src/pages/usercenter/components/AvatarUploadModal.tsx
import { useEffect, useState } from 'react'
import { Avatar, Button, Modal, Slider, Space, Upload, message } from 'antd'
import { UploadOutlined, UserOutlined } from '@ant-design/icons'
import Cropper, { type Area } from 'react-easy-crop'
import { uploadUserCenterAvatar } from '@/api/auth'
import './avatar-upload.css'

type Props = {
  open: boolean
  avatar?: string | null
  onClose: () => void
  onUploaded: () => void
}

const ACCEPTED = ['image/jpeg', 'image/png', 'image/webp']
const MAX_SIZE = 2 * 1024 * 1024
const CROP_SIZE = 320

export function AvatarUploadModal({ open, avatar, onClose, onUploaded }: Props) {
  const [source, setSource] = useState('')
  const [fileName, setFileName] = useState('')
  const [crop, setCrop] = useState({ x: 0, y: 0 })
  const [zoom, setZoom] = useState(1)
  const [croppedAreaPixels, setCroppedAreaPixels] = useState<Area | null>(null)
  const [previewUrl, setPreviewUrl] = useState('')
  const [uploading, setUploading] = useState(false)

  useEffect(() => {
    if (!open) {
      resetSource()
    }
  }, [open])

  function resetSource() {
    if (source) {
      URL.revokeObjectURL(source)
    }
    setSource('')
    setFileName('')
    setPreviewUrl('')
    setCrop({ x: 0, y: 0 })
    setZoom(1)
    setCroppedAreaPixels(null)
  }

  async function onFileChange(file: File) {
    if (!ACCEPTED.includes(file.type)) {
      message.warning('仅支持 JPG、PNG 和 WebP 图片')
      return
    }
    if (file.size > MAX_SIZE) {
      message.warning('图片大小不能超过 2MB')
      return
    }
    if (source) {
      URL.revokeObjectURL(source)
    }
    setFileName(file.name)
    setSource(URL.createObjectURL(file))
    setPreviewUrl('')
  }

  function onCropComplete(_area: Area, areaPixels: Area) {
    setCroppedAreaPixels(areaPixels)
    void updatePreview(areaPixels)
  }

  async function updatePreview(areaPixels: Area) {
    if (!source) return
    const blob = await cropToBlob(source, areaPixels)
    if (blob) {
      setPreviewUrl(URL.createObjectURL(blob))
    }
  }

  async function uploadAvatar() {
    if (!source || !croppedAreaPixels) {
      message.warning('请先选择头像图片')
      return
    }
    const blob = await cropToBlob(source, croppedAreaPixels)
    if (!blob) {
      message.warning('头像图片导出失败')
      return
    }

    setUploading(true)
    try {
      await uploadUserCenterAvatar(new File([blob], 'avatar.png', { type: 'image/png' }))
      message.success('头像已更新')
      onUploaded()
      onClose()
    } catch {
      // 错误提示由拦截器统一处理
    } finally {
      setUploading(false)
    }
  }

  const hasSource = Boolean(source)

  return (
    <Modal
      open={open}
      title="上传头像"
      footer={
        <Space>
          <span className="avatar-upload__hint">{fileName || '仅支持 JPG、PNG 和 WebP 图片'}</span>
          <Button onClick={onClose}>取消</Button>
          {hasSource ? (
            <Button onClick={() => document.getElementById('avatar-file-input')?.click()}>
              重新选择
            </Button>
          ) : null}
          <Button
            type="primary"
            icon={<UploadOutlined />}
            loading={uploading}
            disabled={!hasSource}
            onClick={() => void uploadAvatar()}
          >
            裁剪并上传
          </Button>
        </Space>
      }
      onCancel={onClose}
    >
      <div className="avatar-upload-modal">
        {hasSource ? (
          <div className="avatar-upload-modal__editor">
            <div className="avatar-upload-modal__cropper">
              <Cropper
                image={source}
                crop={crop}
                zoom={zoom}
                aspect={1}
                cropShape="round"
                showGrid={false}
                onCropChange={setCrop}
                onZoomChange={setZoom}
                onCropComplete={onCropComplete}
              />
            </div>
            <div className="avatar-upload-modal__preview-panel">
              <div className="avatar-upload-modal__preview">
                {previewUrl ? <img src={previewUrl} alt="裁剪预览" /> : null}
              </div>
              <div className="mt-3 text-center text-sm text-[var(--ant-color-text-secondary)]">实时预览</div>
            </div>
            <div className="avatar-upload-modal__zoom">
              <Slider min={1} max={4} step={0.01} value={zoom} onChange={setZoom} />
            </div>
          </div>
        ) : (
          <div className="avatar-upload-modal__empty">
            <Avatar size={96} src={avatar || undefined} icon={<UserOutlined />} />
            <Upload accept={ACCEPTED.join(',')} showUploadList={false} beforeUpload={onFileChange}>
              <Button type="primary" icon={<UploadOutlined />} className="mt-4">
                选择图片
              </Button>
            </Upload>
          </div>
        )}
        <input
          id="avatar-file-input"
          type="file"
          accept={ACCEPTED.join(',')}
          className="hidden"
          onChange={(e) => {
            const file = e.target.files?.[0]
            e.target.value = ''
            if (file) {
              void onFileChange(file)
            }
          }}
        />
      </div>
    </Modal>
  )
}

function createImage(src: string) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const image = new Image()
    image.onload = () => resolve(image)
    image.onerror = () => reject(new Error('图片加载失败'))
    image.src = src
  })
}

async function cropToBlob(imageSrc: string, area: Area) {
  try {
    const image = await createImage(imageSrc)
    const canvas = document.createElement('canvas')
    canvas.width = CROP_SIZE
    canvas.height = CROP_SIZE
    const ctx = canvas.getContext('2d')
    if (!ctx) return null

    ctx.drawImage(
      image,
      area.x,
      area.y,
      area.width,
      area.height,
      0,
      0,
      CROP_SIZE,
      CROP_SIZE,
    )

    return new Promise<Blob | null>((resolve) => {
      canvas.toBlob((blob) => resolve(blob), 'image/png', 0.92)
    })
  } catch {
    return null
  }
}

// web/admin/src/views/usercenter/components/AvatarUploadModal.vue
<script setup lang="ts">
import { authApi } from '@/api'
import { computed, reactive, ref, watch } from 'vue'
import { Cropper } from 'vue-advanced-cropper'
import 'vue-advanced-cropper/dist/style.css'

const props = defineProps<{
  show: boolean
  avatar?: string | null
}>()

const emit = defineEmits<{
  (e: 'update:show', value: boolean): void
  (e: 'uploaded'): void
}>()

const fileInputRef = ref<HTMLInputElement | null>(null)
const cropperRef = ref<any>(null)

const state = reactive({
  source: '',
  previewUrl: '',
  fileName: '',
  uploading: false,
})

const modalShow = computed({
  get: () => props.show,
  set: (value: boolean) => emit('update:show', value),
})

watch(
  () => props.show,
  (show) => {
    if (!show) {
      resetSource()
    }
  },
)

function openFilePicker() {
  fileInputRef.value?.click()
}

function onFileChange(event: Event) {
  const input = event.target as HTMLInputElement
  const file = input.files?.[0]
  input.value = ''
  if (!file) {
    return
  }
  if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) {
    window.$message.warning('仅支持 JPG、PNG 和 WebP 图片，裁剪后上传')
    return
  }
  resetSource()
  state.fileName = file.name
  state.source = URL.createObjectURL(file)
  updatePreview()
}

async function uploadAvatar() {
  const canvas = cropperRef.value?.getResult?.().canvas
  if (!canvas) {
    window.$message.warning('请先选择头像图片')
    return
  }

  state.uploading = true
  try {
    const blob = await canvasToBlob(canvas)
    await authApi.uploadUserCenterAvatar(new File([blob], 'avatar.png', { type: 'image/png' }))
    window.$message.success('头像已更新')
    emit('uploaded')
    modalShow.value = false
  } finally {
    state.uploading = false
  }
}

function onCropperChange() {
  updatePreview()
}

function updatePreview() {
  window.requestAnimationFrame(() => {
    const canvas = cropperRef.value?.getResult?.().canvas
    state.previewUrl = canvas ? canvas.toDataURL('image/png') : ''
  })
}

function canvasToBlob(canvas: HTMLCanvasElement) {
  return new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob) {
          resolve(blob)
          return
        }
        reject(new Error('头像图片导出失败'))
      },
      'image/png',
      0.92,
    )
  })
}

function resetSource() {
  if (state.source) {
    URL.revokeObjectURL(state.source)
  }
  state.source = ''
  state.previewUrl = ''
  state.fileName = ''
}
</script>

<template>
  <NModal
    v-model:show="modalShow"
    preset="card"
    :title="'上传头像'"
    class="max-w-150"
    :bordered="false"
    :mask-closable="!state.uploading"
  >
    <input
      ref="fileInputRef"
      class="hidden"
      type="file"
      accept="image/jpeg,image/png,image/webp"
      @change="onFileChange"
    />

    <div class="avatar-upload-modal">
      <div v-if="state.source" class="avatar-editor">
        <div class="avatar-cropper-wrap">
          <Cropper
            ref="cropperRef"
            class="avatar-cropper"
            :src="state.source"
            :stencil-props="{ aspectRatio: 1 }"
            :canvas="{ width: 320, height: 320 }"
            @change="onCropperChange"
          />
        </div>
        <div class="avatar-preview-panel">
          <div class="avatar-preview">
            <img v-if="state.previewUrl" :src="state.previewUrl" alt="" />
          </div>
          <div class="mt-3 text-sm text-[var(--text-color-3)]">实时预览</div>
        </div>
      </div>
      <div v-else class="avatar-empty">
        <NAvatar v-if="avatar" round :size="96" :src="avatar" />
        <NAvatar v-else round :size="96">
          <NovaIcon icon="icon-park-outline:user" :size="40" />
        </NAvatar>
        <NButton secondary type="primary" class="mt-4" @click="openFilePicker">
          <template #icon>
            <NovaIcon icon="icon-park-outline:upload-picture" />
          </template>
          选择图片
        </NButton>
      </div>
    </div>

    <template #footer>
      <NSpace justify="space-between" align="center">
        <div class="max-w-70 truncate text-sm text-[var(--text-color-3)]">
          {{ state.fileName || '仅支持 JPG、PNG 和 WebP 图片，裁剪后上传' }}
        </div>
        <NSpace>
          <NButton @click="modalShow = false"> 取消 </NButton>
          <NButton v-if="state.source" secondary @click="openFilePicker"> 重新选择 </NButton>
          <NButton type="primary" :loading="state.uploading" @click="uploadAvatar">
            裁剪并上传
          </NButton>
        </NSpace>
      </NSpace>
    </template>
  </NModal>
</template>

<style scoped>
.avatar-upload-modal {
  min-height: 360px;
}

.avatar-editor {
  display: grid;
  grid-template-columns: minmax(0, 1fr) 180px;
  gap: 16px;
  align-items: stretch;
}

.avatar-cropper-wrap {
  height: min(56vh, 420px);
  overflow: hidden;
  border: 1px solid var(--border-color);
  border-radius: 8px;
}

.avatar-cropper {
  height: 100%;
  width: 100%;
  background: var(--body-color);
}

.avatar-preview-panel {
  min-height: 360px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--border-color);
  border-radius: 8px;
  padding: 16px;
}

.avatar-preview {
  width: 128px;
  height: 128px;
  overflow: hidden;
  border-radius: 999px;
  background: var(--body-color);
  box-shadow: inset 0 0 0 1px var(--border-color);
}

.avatar-preview img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.avatar-empty {
  min-height: 360px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border: 1px dashed var(--border-color);
  border-radius: 8px;
}

@media (max-width: 640px) {
  .avatar-editor {
    grid-template-columns: 1fr;
  }

  .avatar-preview-panel {
    min-height: 190px;
  }
}
</style>
