// web/portal/src/pages/usercenter/index.tsx
import { useEffect, useState } from 'react'
import {
  Avatar,
  Button,
  Card,
  Col,
  Descriptions,
  Divider,
  Form,
  Input,
  Modal,
  Row,
  Spin,
  Switch,
  Tabs,
  Typography,
  message,
} from 'antd'
import { UserOutlined } from '@ant-design/icons'
import * as authApi from '@/api/auth'
import type { PortalMeResponse, PortalProfileData } from '@/api/auth'
import { useAuthStore } from '@/stores/auth'
import { encryptPasswords } from '@/utils/security'
import { resolveFileUrl } from '@/utils/file'
import { isValidEmail } from '@/utils/validate'
import { PasswordStrength } from '@/components/common/PasswordStrength'
import { AvatarUploadModal } from './components/AvatarUploadModal'
import './usercenter.css'

const mapNames = (items?: { id: string; name: string }[]) =>
  (items ?? []).map((item) => item.name).filter(Boolean).join(' / ')

const displayValue = (value: unknown) => (value ? String(value) : '未设置')

type BindConfirmState = {
  show: boolean
  type: 'phone' | 'email'
  password: string
  loading: boolean
}

export function UserCenterPage() {
  const refreshUserInfo = useAuthStore((s) => s.refreshUserInfo)

  const [loading, setLoading] = useState(true)
  const [me, setMe] = useState<PortalMeResponse | null>(null)
  const [avatarModalShow, setAvatarModalShow] = useState(false)

  const [profileForm] = Form.useForm()
  const [passwordForm] = Form.useForm()
  const [phoneForm] = Form.useForm()
  const [emailForm] = Form.useForm()

  const [savingProfile, setSavingProfile] = useState(false)
  const [savingPassword, setSavingPassword] = useState(false)
  const [savingBind, setSavingBind] = useState(false)

  const newPassword = Form.useWatch('new_password', passwordForm) || ''

  const [bindConfirm, setBindConfirm] = useState<BindConfirmState>({
    show: false,
    type: 'phone',
    password: '',
    loading: false,
  })

  useEffect(() => {
    void loadMe()
  }, [])

  async function loadMe() {
    setLoading(true)
    try {
      await refreshMe()
    } finally {
      setLoading(false)
    }
  }

  async function refreshMe() {
    const data = await refreshUserInfo()
    setMe(data)
    syncForms(data)
  }

  function syncForms(data: PortalMeResponse) {
    const profile = (data.profile ?? {}) as PortalProfileData
    profileForm.setFieldsValue({
      name: data.name ?? profile.name ?? '',
      nickname: data.nickname ?? profile.nickname ?? '',
      signature: profile.signature ?? '',
    })
    phoneForm.setFieldsValue({
      phone: profile.phone ?? '',
      phone_login_enabled: Boolean(profile.phone_login_enabled),
    })
    emailForm.setFieldsValue({
      email: profile.email ?? '',
      email_login_enabled: Boolean(profile.email_login_enabled),
    })
  }

  async function saveProfile() {
    setSavingProfile(true)
    try {
      const values = await profileForm.validateFields()
      await authApi.updateUserCenterProfile({
        name: values.name || null,
        nickname: values.nickname || null,
        signature: values.signature || null,
      })
      await refreshMe()
      message.success('保存成功')
    } finally {
      setSavingProfile(false)
    }
  }

  async function savePassword() {
    const values = await passwordForm.validateFields()
    if (values.new_password !== values.confirm_password) {
      message.warning('两次输入的新密码不一致')
      return
    }
    setSavingPassword(true)
    try {
      const encrypted = await encryptPasswords({
        old_password: values.old_password,
        new_password: values.new_password,
      })
      await authApi.updateUserCenterPassword({
        old_password: encrypted.values.old_password || '',
        new_password: encrypted.values.new_password || '',
        password_key_id: encrypted.password_key_id,
      })
      passwordForm.resetFields()
      message.success('密码已更新')
    } finally {
      setSavingPassword(false)
    }
  }

  async function savePhone() {
    await phoneForm.validateFields()
    openBindConfirm('phone')
  }

  async function saveEmail() {
    const values = await emailForm.validateFields()
    const email = (values.email ?? '').trim()
    if (email && !isValidEmail(email)) {
      message.warning('请输入有效邮箱')
      return
    }
    openBindConfirm('email')
  }

  function openBindConfirm(type: 'phone' | 'email') {
    setBindConfirm({ show: true, type, password: '', loading: false })
  }

  async function confirmBind() {
    if (!bindConfirm.password) {
      message.warning('请输入当前密码')
      return
    }
    setBindConfirm((s) => ({ ...s, loading: true }))
    setSavingBind(true)
    try {
      const encrypted = await encryptPasswords({ password: bindConfirm.password })
      if (bindConfirm.type === 'phone') {
        const values = phoneForm.getFieldsValue()
        await authApi.updateUserCenterPhone({
          password: encrypted.values.password || '',
          password_key_id: encrypted.password_key_id,
          phone: values.phone || null,
          phone_login_enabled: Boolean(values.phone_login_enabled),
        })
      } else {
        const values = emailForm.getFieldsValue()
        await authApi.updateUserCenterEmail({
          password: encrypted.values.password || '',
          password_key_id: encrypted.password_key_id,
          email: (values.email ?? '').trim() || null,
          email_login_enabled: Boolean(values.email_login_enabled),
        })
      }
      setBindConfirm((s) => ({ ...s, show: false, password: '' }))
      await refreshMe()
      message.success('绑定已更新')
    } finally {
      setBindConfirm((s) => ({ ...s, loading: false }))
      setSavingBind(false)
    }
  }

  const profile = (me?.profile ?? {}) as PortalProfileData
  const displayName = me?.nickname || me?.name || '-'
  const avatarUrl = resolveFileUrl(me?.avatar || profile.avatar)
  const roleNames = mapNames(me?.role_id_names)
  const contactParts = [profile.phone, profile.email].filter(Boolean)
  const contactText = contactParts.length ? contactParts.join(' / ') : '未设置'

  const tabItems = [
    {
      key: 'basic_info',
      label: '基本信息',
      children: (
        <Form form={profileForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item label="账号">
            <Input value={me?.account} disabled />
          </Form.Item>
          <Form.Item
            name="name"
            label="姓名"
            rules={[{ max: 64, message: '姓名最多 64 个字符' }]}
          >
            <Input placeholder="请输入姓名" allowClear />
          </Form.Item>
          <Form.Item
            name="nickname"
            label="昵称"
            rules={[{ max: 64, message: '昵称最多 64 个字符' }]}
          >
            <Input placeholder="请输入昵称" allowClear />
          </Form.Item>
          <Form.Item name="signature" label="个性签名">
            <Input.TextArea rows={3} placeholder="介绍一下自己" allowClear />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingProfile} onClick={() => void saveProfile()}>
              保存
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'password',
      label: '密码',
      children: (
        <Form form={passwordForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item
            name="old_password"
            label="旧密码"
            rules={[{ required: true, message: '请输入旧密码' }]}
          >
            <Input.Password placeholder="请输入旧密码" />
          </Form.Item>
          <Form.Item
            name="new_password"
            label="新密码"
            rules={[{ required: true, message: '请输入新密码' }]}
          >
            <Input.Password placeholder="至少 8 个字符，含大小写、数字与特殊字符" />
          </Form.Item>
          <PasswordStrength password={newPassword} />
          <Form.Item
            name="confirm_password"
            label="确认密码"
            dependencies={['new_password']}
            rules={[
              { required: true, message: '请确认新密码' },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('new_password') === value) {
                    return Promise.resolve()
                  }
                  return Promise.reject(new Error('两次输入的新密码不一致'))
                },
              }),
            ]}
          >
            <Input.Password placeholder="再次输入新密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingPassword} onClick={() => void savePassword()}>
              修改密码
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'phone',
      label: '手机号',
      children: (
        <Form form={phoneForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item name="phone" label="手机号">
            <Input placeholder="请输入手机号" allowClear />
          </Form.Item>
          <Form.Item
            name="phone_login_enabled"
            label="启用手机号登录"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingBind} onClick={() => void savePhone()}>
              修改手机号
            </Button>
          </Form.Item>
        </Form>
      ),
    },
    {
      key: 'email',
      label: '邮箱',
      children: (
        <Form form={emailForm} layout="vertical" className="max-w-140 min-w-0">
          <Form.Item
            name="email"
            label="邮箱"
            rules={[{ type: 'email', message: '邮箱格式不正确' }]}
          >
            <Input placeholder="your@example.com" allowClear />
          </Form.Item>
          <Form.Item
            name="email_login_enabled"
            label="启用邮箱登录"
            valuePropName="checked"
          >
            <Switch />
          </Form.Item>
          <Form.Item>
            <Button type="primary" loading={savingBind} onClick={() => void saveEmail()}>
              修改邮箱
            </Button>
          </Form.Item>
        </Form>
      ),
    },
  ]

  return (
    <div className="w-full min-w-0">
      <Spin spinning={loading}>
        <Row gutter={[16, 16]}>
          <Col xs={24} lg={7} className="min-w-0">
            <Card className="h-full" styles={{ body: { minWidth: 0 } }}>
              <div className="flex flex-col items-center text-center">
                <button
                  type="button"
                  className="avatar-trigger"
                  title="更换头像"
                  onClick={() => setAvatarModalShow(true)}
                >
                  <Avatar
                    size={104}
                    src={avatarUrl}
                    icon={<UserOutlined />}
                    style={{ display: 'block' }}
                  />
                </button>
                <div className="mt-4 max-w-full truncate text-xl font-medium">
                  {displayName}
                </div>
                <div className="mt-1 max-w-full truncate text-sm text-[var(--ant-color-text-secondary)]">
                  {me?.account}
                </div>
              </div>

              <Divider />

              <Descriptions column={1} labelStyle={{ width: 72 }}>
                <Descriptions.Item label="角色">
                  {roleNames || '未设置'}
                </Descriptions.Item>
                <Descriptions.Item label="联系方式">{contactText}</Descriptions.Item>
              </Descriptions>

              <Divider />

              <div className="text-sm font-medium">个性签名</div>
              <div className="mt-2 min-h-16 rounded border border-[var(--ant-color-border)] p-3 text-sm text-[var(--ant-color-text-secondary)]">
                {displayValue(profile.signature)}
              </div>
            </Card>
          </Col>

          <Col xs={24} lg={17} className="min-w-0">
            <Card className="w-full min-w-0" styles={{ body: { minWidth: 0 } }}>
              <Tabs items={tabItems} />
            </Card>
          </Col>
        </Row>
      </Spin>

      <Modal
        open={bindConfirm.show}
        title={bindConfirm.type === 'phone' ? '确认更新手机号' : '确认更新邮箱'}
        okText="确认"
        cancelText="取消"
        confirmLoading={bindConfirm.loading}
        maskClosable={false}
        onOk={() => void confirmBind()}
        onCancel={() => setBindConfirm((s) => ({ ...s, show: false }))}
      >
        <Form layout="vertical">
          <Form.Item label="当前密码">
            <Input.Password
              value={bindConfirm.password}
              placeholder="请输入当前密码"
              onChange={(e) => setBindConfirm((s) => ({ ...s, password: e.target.value }))}
              onPressEnter={() => void confirmBind()}
            />
          </Form.Item>
        </Form>
        <Typography.Text type="secondary">
          为保障账号安全，修改{bindConfirm.type === 'phone' ? '手机号' : '邮箱'}需验证当前密码。
        </Typography.Text>
      </Modal>

      <AvatarUploadModal
        open={avatarModalShow}
        avatar={avatarUrl}
        onClose={() => setAvatarModalShow(false)}
        onUploaded={() => void refreshMe()}
      />
    </div>
  )
}

// web/portal-nuxt/app/pages/usercenter/index.vue
<script setup lang="ts">
const authStore = useAuthStore()
const toast = useToast()
const avatarModalOpen = ref(false)

const state = reactive({
  loading: false,
  savingProfile: false,
  savingPassword: false,
  savingEmail: false,
  activeTab: 'basic_info',
  profileForm: {
    name: '',
    nickname: '',
    signature: '',
  },
  passwordForm: {
    oldPassword: '',
    newPassword: '',
    confirmPassword: '',
  },
  emailForm: {
    email: '',
    password: '',
    emailLoginEnabled: true,
  },
  bindConfirm: {
    show: false,
    type: '' as 'phone' | 'email',
    password: '',
    loading: false,
  },
})

const profile = computed(() => authStore.userInfo ?? {})

function resolveAvatarUrl(value?: string | null) {
  if (!value) return undefined
  const raw = String(value).trim()
  if (!raw) return undefined
  if (/^(https?:|data:|blob:)/i.test(raw)) return raw
  try {
    const baseURL = useRuntimeConfig().public.apiBaseUrl
    if (baseURL) return `${baseURL.replace(/\/$/, '')}/${raw.replace(/^\//, '')}`
  } catch {
    // ignore
  }
  return raw
}

const avatarUrl = computed(() => resolveAvatarUrl(profile.value?.avatar))
const displayName = computed(
  () => authStore.userInfo?.nickname || authStore.userInfo?.account || '-',
)

function syncForms() {
  const u = authStore.userInfo
  if (!u) return
  state.profileForm.name = u.name ?? ''
  state.profileForm.nickname = u.nickname ?? ''
  state.profileForm.signature = u.signature ?? ''
  state.emailForm.email = u.email ?? ''
}

// 初始加载
onMounted(async () => {
  state.loading = true
  try {
    await authStore.refreshUserInfo()
    syncForms()
  } finally {
    state.loading = false
  }
})

async function saveProfile() {
  state.savingProfile = true
  try {
    await useHttp().post('/api/v1/portal/user-center/profile/update', {
      name: state.profileForm.name || null,
      nickname: state.profileForm.nickname || null,
      signature: state.profileForm.signature || null,
    })
    await authStore.refreshUserInfo()
    toast.add({ title: '保存成功', color: 'none' })
  } catch {
    // error toast by interceptor
  } finally {
    state.savingProfile = false
  }
}

async function savePassword() {
  if (state.passwordForm.newPassword !== state.passwordForm.confirmPassword) {
    toast.add({ title: '错误', description: '两次密码输入不一致', color: 'error' })
    return
  }
  state.savingPassword = true
  try {
    const { data: key } = await useHttp().get('/api/v1/portal/password-key')
    const { encryptPassword } = await import('~/utils/crypto')
    const oldEncrypted = await encryptPassword(state.passwordForm.oldPassword, {
      key_id: key.key_id,
      public_key: key.public_key,
    })
    const newEncrypted = await encryptPassword(state.passwordForm.newPassword, {
      key_id: key.key_id,
      public_key: key.public_key,
    })
    await useHttp().post('/api/v1/portal/user-center/password/update', {
      old_password: oldEncrypted.encrypted,
      new_password: newEncrypted.encrypted,
      password_key_id: key.key_id,
    })
    state.passwordForm.oldPassword = ''
    state.passwordForm.newPassword = ''
    state.passwordForm.confirmPassword = ''
    toast.add({ title: '密码已更新', color: 'success' })
  } catch {
    // error toast by interceptor
  } finally {
    state.savingPassword = false
  }
}

function openBindConfirm(type: 'phone' | 'email') {
  state.bindConfirm.type = type
  state.bindConfirm.password = ''
  state.bindConfirm.show = true
}

async function confirmBind() {
  if (!state.bindConfirm.password) {
    toast.add({ title: '错误', description: '请输入当前密码', color: 'error' })
    return
  }
  const isEmail = state.bindConfirm.type === 'email'
  state.bindConfirm.loading = true
  state.savingEmail = isEmail
  try {
    const { data: key } = await useHttp().get('/api/v1/portal/password-key')
    const { encryptPassword } = await import('~/utils/crypto')
    const encrypted = await encryptPassword(state.bindConfirm.password, {
      key_id: key.key_id,
      public_key: key.public_key,
    })

    if (isEmail) {
      if (!state.emailForm.email || !/\S+@\S+\.\S+/.test(state.emailForm.email)) {
        toast.add({ title: '错误', description: '邮箱格式不正确', color: 'error' })
        return
      }
      await useHttp().post('/api/v1/portal/user-center/email/update', {
        password: encrypted.encrypted,
        email: state.emailForm.email.trim() || null,
        email_login_enabled: state.emailForm.emailLoginEnabled,
        password_key_id: key.key_id,
      })
    }
    state.bindConfirm.show = false
    state.bindConfirm.password = ''
    await authStore.refreshUserInfo()
    syncForms()
    toast.add({ title: '绑定已更新', color: 'success' })
  } catch {
    // error toast by interceptor
  } finally {
    state.bindConfirm.loading = false
    state.savingEmail = false
  }
}

function refreshMe() {
  authStore.refreshUserInfo().then(syncForms)
}
</script>

<template>
  <div class="w-full min-w-0">
    <div v-if="state.loading" class="flex justify-center py-16">
      <UIcon name="i-lucide-loader-circle" class="size-8 animate-spin text-muted" />
    </div>
    <template v-else>
      <div class="flex flex-col lg:flex-row gap-4 p-6">
        <!-- Left card -->
        <UCard class="w-full lg:w-72 shrink-0 h-fit">
          <div class="flex flex-col items-center text-center py-2">
            <button
              type="button"
              title="更换头像"
              class="avatar-trigger"
              @click="avatarModalOpen = true"
            >
              <UAvatar v-if="avatarUrl" :src="avatarUrl" size="2xl" class="rounded-full" />
              <UAvatar v-else size="2xl" icon="i-lucide-user" class="rounded-full" />
            </button>
            <div class="mt-3 text-lg font-semibold truncate max-w-full">
              {{ displayName }}
            </div>
            <div class="text-sm text-muted">
              {{ authStore.userInfo?.account }}
            </div>
          </div>

          <USeparator class="my-3" />

          <dl class="space-y-2 text-sm">
            <div class="flex justify-between">
              <dt class="text-muted">昵称</dt>
              <dd class="font-medium">{{ authStore.userInfo?.nickname || '未设置' }}</dd>
            </div>
            <div class="flex justify-between">
              <dt class="text-muted">邮箱</dt>
              <dd class="font-medium">{{ authStore.userInfo?.email || '未设置' }}</dd>
            </div>
          </dl>

          <USeparator class="my-3" />

          <div class="text-sm font-medium mb-1">个性签名</div>
          <div class="min-h-12 rounded p-2 text-sm text-muted bg-muted">
            {{ authStore.userInfo?.signature || '未设置' }}
          </div>
        </UCard>

        <!-- Right card with tabs -->
        <UCard class="flex-1 min-w-0">
          <UTabs
            v-model="state.activeTab"
            :items="[
              { label: '基本信息', value: 'basic_info' },
              { label: '密码', value: 'password' },
              { label: '邮箱', value: 'email' },
            ]"
          >
            <template #content="{ item }">
              <!-- Basic Info -->
              <div v-if="item.value === 'basic_info'" class="space-y-4 pt-4 max-w-lg">
                <UFormField label="账号">
                  <UInput :model-value="authStore.userInfo?.account" disabled class="w-full" />
                </UFormField>
                <UFormField label="姓名">
                  <UInput v-model="state.profileForm.name" class="w-full" />
                </UFormField>
                <UFormField label="昵称">
                  <UInput v-model="state.profileForm.nickname" class="w-full" />
                </UFormField>
                <UFormField label="个性签名">
                  <UTextarea v-model="state.profileForm.signature" class="w-full" />
                </UFormField>
                <UButton color="primary" :loading="state.savingProfile" @click="saveProfile">
                  保存
                </UButton>
              </div>

              <!-- Password -->
              <div v-if="item.value === 'password'" class="space-y-4 pt-4 max-w-lg">
                <UFormField label="旧密码">
                  <UInput v-model="state.passwordForm.oldPassword" type="password" class="w-full" />
                </UFormField>
                <UFormField label="新密码">
                  <UInput v-model="state.passwordForm.newPassword" type="password" class="w-full" />
                </UFormField>
                <UFormField label="确认密码">
                  <UInput
                    v-model="state.passwordForm.confirmPassword"
                    type="password"
                    class="w-full"
                  />
                </UFormField>
                <UButton color="primary" :loading="state.savingPassword" @click="savePassword">
                  修改密码
                </UButton>
              </div>

              <!-- Email -->
              <div v-if="item.value === 'email'" class="space-y-4 pt-4 max-w-lg">
                <UFormField label="邮箱">
                  <UInput v-model="state.emailForm.email" type="email" class="w-full" />
                </UFormField>
                <UFormField label="启用邮箱登录">
                  <USwitch v-model="state.emailForm.emailLoginEnabled" />
                </UFormField>
                <UButton
                  color="primary"
                  :loading="state.savingEmail"
                  @click="openBindConfirm('email')"
                >
                  修改邮箱
                </UButton>
              </div>
            </template>
          </UTabs>
        </UCard>
      </div>
    </template>

    <!-- Bind confirm modal -->
    <UModal v-model:open="state.bindConfirm.show">
      <template #title>确认更新</template>
      <template #body>
        <UFormField label="当前密码">
          <UInput
            v-model="state.bindConfirm.password"
            type="password"
            placeholder="请输入当前密码"
            class="w-full"
            @keydown.enter="confirmBind"
          />
        </UFormField>
      </template>
      <template #footer>
        <div class="flex justify-end gap-2 w-full">
          <UButton color="neutral" variant="ghost" @click="state.bindConfirm.show = false"
            >取消</UButton
          >
          <UButton :loading="state.bindConfirm.loading" @click="confirmBind">确认</UButton>
        </div>
      </template>
    </UModal>

    <AvatarCropperModal v-model:open="avatarModalOpen" :avatar="avatarUrl" @uploaded="refreshMe" />
  </div>
</template>

<style scoped>
.avatar-trigger {
  border: 0;
  border-radius: 999px;
  background: transparent;
  padding: 0;
  cursor: pointer;
  line-height: 0;
  transition:
    background-color 0.2s,
    box-shadow 0.2s,
    transform 0.2s;
}
.avatar-trigger:hover {
  box-shadow:
    0 0 0 3px var(--ui-bg),
    0 0 0 5px var(--ui-primary);
  transform: translateY(-1px);
  outline: none;
}
</style>
