// web/portal/src/components/common/CaptchaInput.tsx
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react'
import { Input, Spin } from 'antd'
import * as authApi from '@/api/auth'

export type CaptchaInputHandle = {
  refresh: () => Promise<void>
}

type Props = {
  captchaId: string
  captchaValue: string
  onCaptchaIdChange: (value: string) => void
  onCaptchaValueChange: (value: string) => void
}

export const CaptchaInput = forwardRef<CaptchaInputHandle, Props>(function CaptchaInput(
  { captchaValue, onCaptchaIdChange, onCaptchaValueChange },
  ref,
) {
  const [loading, setLoading] = useState(false)
  const [imageBase64, setImageBase64] = useState('')
  const idChangeRef = useRef(onCaptchaIdChange)
  const valueChangeRef = useRef(onCaptchaValueChange)
  idChangeRef.current = onCaptchaIdChange
  valueChangeRef.current = onCaptchaValueChange

  async function refresh() {
    setLoading(true)
    try {
      const response = await authApi.captcha('svg')
      idChangeRef.current(response.data.captcha_id)
      valueChangeRef.current('')
      setImageBase64(response.data.image_base64)
    } finally {
      setLoading(false)
    }
  }

  useImperativeHandle(ref, () => ({ refresh }))

  useEffect(() => {
    void refresh()
  }, [])

  const imageSrc = imageBase64 ? `data:image/svg+xml;base64,${imageBase64}` : ''

  return (
    <div className="grid grid-cols-[minmax(0,1fr)_140px] gap-2.5 items-center">
      <Input
        value={captchaValue}
        placeholder="请输入验证码"
        allowClear
        onChange={(e) => onCaptchaValueChange(e.target.value)}
      />
      <button
        type="button"
        className="h-11 w-140px overflow-hidden rounded-md border border-gray-200 bg-gray-50 p-0 cursor-pointer disabled:cursor-wait"
        disabled={loading}
        onClick={() => void refresh()}
      >
        <Spin spinning={loading} size="small">
          {imageSrc ? <img src={imageSrc} alt="验证码" className="block h-11 w-140px" /> : null}
        </Spin>
      </button>
    </div>
  )
})

// admin/src/components/common/CaptchaInput.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import { authApi } from '@/api'
import { computed, onMounted, ref } from 'vue'

withDefaults(
  defineProps<{
    size?: 'tiny' | 'small' | 'medium' | 'large'
  }>(),
  {
    size: 'large',
  },
)

const captchaId = defineModel<string>('captchaId', { required: true })
const captchaValue = defineModel<string>('captchaValue', { required: true })
const loading = ref(false)
const imageBase64 = ref('')

function getValues() {
  return {
    captcha_id: captchaId.value,
    captcha_value: captchaValue.value,
  }
}

const imageSrc = computed(() =>
  imageBase64.value ? `data:image/svg+xml;base64,${imageBase64.value}` : '',
)

async function refresh() {
  loading.value = true
  try {
    const response = await authApi.captcha()
    captchaId.value = response.data.captcha_id
    captchaValue.value = ''
    imageBase64.value = response.data.image_base64
  } finally {
    loading.value = false
  }
}

onMounted(refresh)

defineExpose({ refresh, getValues })
</script>

<template>
  <div
    class="captcha-input"
    :class="`captcha-input--${size}`"
  >
    <NInput
      v-model:value="captchaValue"
      class="captcha-input__field"
      :size="size"
      :placeholder="'请输入验证码'"
      clearable
    />
    <button
      class="captcha-image"
      type="button"
      :disabled="loading"
      aria-label="刷新验证码"
      @click="refresh"
    >
      <NSpin
        :show="loading"
        size="small"
      >
        <img
          v-if="imageSrc"
          :src="imageSrc"
          alt="验证码"
        >
      </NSpin>
    </button>
  </div>
</template>

<style scoped>
/* 以输入框真实高度为准，图片绝对定位铺满，避免 SVG 撑高 */
.captcha-input {
  display: flex;
  align-items: stretch;
  gap: 10px;
  width: 100%;
}

.captcha-input__field {
  flex: 1;
  min-width: 0;
}

.captcha-image {
  position: relative;
  box-sizing: border-box;
  flex: 0 0 140px;
  width: 140px;
  padding: 0;
  overflow: hidden;
  cursor: pointer;
  line-height: 0;
  /* --n-* 只在 Naive 组件根上定义，兄弟自定义元素取不到；改用自包含变量 + 模式兜底 */
  background: var(--captcha-bg, #f8fafc);
  border: 1px solid var(--captcha-border, #e0e0e6);
  border-radius: var(--border-radius, var(--n-border-radius, 3px));
}

html.dark .captcha-image {
  --captcha-bg: #1a1d24;
  --captcha-border: #2a2f3a;
}

.captcha-image:disabled {
  cursor: wait;
}

.captcha-image :deep(.n-spin-nested-loading),
.captcha-image :deep(.n-spin-container) {
  position: absolute;
  inset: 0;
}

.captcha-image img {
  display: block;
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>
