// admin/src/views/auth/ForgotPassword.vue
<!-- Author: Charlie -->

<script setup lang="ts">
import type { FormItemInst, FormItemRule } from 'naive-ui'
import { authApi } from '@/api'
import CaptchaInput from '@/components/common/CaptchaInput.vue'
import { isValidEmail } from '@/utils'
import { encryptPasswords } from '@/utils/security'
import { type SiteFooterInfo, emptySiteFooter, parseSiteFooter } from '@/composables/siteFooter'
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AuthLayout from './AuthLayout.vue'

const route = useRoute()
const router = useRouter()
const emailItemRef = ref<FormItemInst | null>(null)
const passwordItemRef = ref<FormItemInst | null>(null)
const confirmItemRef = ref<FormItemInst | null>(null)
const captchaItemRef = ref<FormItemInst | null>(null)
const captchaRef = ref<InstanceType<typeof CaptchaInput> | null>(null)
const loading = ref(false)
const siteFooter = ref<SiteFooterInfo>(emptySiteFooter())

onMounted(async () => {
  try {
    const res = await authApi.authOptions()
    siteFooter.value = parseSiteFooter(res?.data)
  } catch {
    // 使用默认页脚
  }
})

const form = reactive({
  email: '',
  token: typeof route.query.token === 'string' ? route.query.token : '',
  password: '',
  confirmPassword: '',
  captcha_id: '',
  captcha_value: '',
})

const isResetMode = computed(() => Boolean(form.token))

const emailRule: FormItemRule = {
  trigger: ['input', 'blur'],
  validator() {
    const text = form.email.trim()
    if (!text) return new Error('请输入登录邮箱')
    if (!isValidEmail(text)) return new Error('请输入有效邮箱')
    return true
  },
}

const passwordRule: FormItemRule = {
  trigger: ['input', 'blur'],
  validator() {
    if (!form.password) return new Error('请输入新密码')
    if (form.password.length < 8) return new Error('密码至少 8 个字符')
    return true
  },
}

const confirmPasswordRule: FormItemRule = {
  trigger: ['input', 'blur'],
  validator() {
    if (!form.confirmPassword) return new Error('请确认密码')
    if (form.confirmPassword !== form.password) return new Error('两次输入的密码不一致')
    return true
  },
}

const captchaRule: FormItemRule = {
  trigger: ['input', 'blur'],
  validator() {
    if (!form.captcha_value.trim()) return new Error('请输入验证码')
    return true
  },
}

async function validateFields(items: Array<FormItemInst | null | undefined>) {
  try {
    await Promise.all(items.filter(Boolean).map((item) => item!.validate()))
    return true
  } catch {
    return false
  }
}

async function sendLink() {
  const ok = await validateFields([emailItemRef.value, captchaItemRef.value])
  if (!ok) return
  loading.value = true
  try {
    await authApi.forgotPassword({
      email: form.email.trim(),
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
    })
    window.$message.success('密码重置链接已发送')
    await captchaRef.value?.refresh()
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}

async function resetPassword() {
  const ok = await validateFields([
    passwordItemRef.value,
    confirmItemRef.value,
    captchaItemRef.value,
  ])
  if (!ok) return
  loading.value = true
  try {
    const encrypted = await encryptPasswords({ password: form.password })
    await authApi.resetPassword({
      token: form.token,
      password: encrypted.values.password,
      password_key_id: encrypted.password_key_id,
      captcha_id: form.captcha_id,
      captcha_value: form.captcha_value,
    })
    window.$message.success('密码已重置，请重新登录')
    router.push('/auth/login')
  } catch {
    await captchaRef.value?.refresh()
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <AuthLayout
    :title="isResetMode ? '重置密码' : '找回密码'"
    :site-footer="siteFooter"
    :description="
      isResetMode
        ? '请设置新密码。重置链接在过期前仅可使用一次。'
        : '请输入已启用管理端登录的邮箱，系统将发送密码重置链接。'
    "
  >
    <template #headerExtra>
      <RouterLink
        class="linkish"
        to="/auth/login"
      >
        返回登录
      </RouterLink>
    </template>

    <form
      class="auth-form"
      @submit.prevent="isResetMode ? resetPassword() : sendLink()"
    >
      <n-form-item
        v-if="!isResetMode"
        ref="emailItemRef"
        :show-label="false"
        :rule="emailRule"
      >
        <n-input
          v-model:value="form.email"
          size="large"
          clearable
          placeholder="登录邮箱"
        />
      </n-form-item>

      <template v-if="isResetMode">
        <n-form-item
          ref="passwordItemRef"
          :show-label="false"
          :rule="passwordRule"
        >
          <n-input
            v-model:value="form.password"
            size="large"
            type="password"
            show-password-on="click"
            placeholder="新密码（至少 8 位）"
          />
        </n-form-item>
        <PasswordStrengthBar :password="form.password" />
        <n-form-item
          ref="confirmItemRef"
          :show-label="false"
          :rule="confirmPasswordRule"
        >
          <n-input
            v-model:value="form.confirmPassword"
            size="large"
            type="password"
            show-password-on="click"
            placeholder="确认新密码"
          />
        </n-form-item>
      </template>

      <n-form-item
        ref="captchaItemRef"
        :show-label="false"
        :rule="captchaRule"
      >
        <CaptchaInput
          ref="captchaRef"
          v-model:captcha-id="form.captcha_id"
          v-model:captcha-value="form.captcha_value"
          size="large"
        />
      </n-form-item>

      <n-button
        type="primary"
        size="large"
        block
        attr-type="submit"
        :loading="loading"
      >
        {{ isResetMode ? '重置密码' : '发送重置链接' }}
      </n-button>

      <div
        v-if="isResetMode"
        class="auth-form-row"
        style="margin-top: 12px"
      >
        <RouterLink to="/auth/forgot-password">
          重新申请链接
        </RouterLink>
      </div>
    </form>
  </AuthLayout>
</template>

// web/portal/src/pages/auth/forgot-password.tsx
import { useRef, useState } from 'react'
import { Button, ConfigProvider, Form, Input, message } from 'antd'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import * as authApi from '@/api/auth'
import { CaptchaInput, type CaptchaInputHandle } from '@/components/common/CaptchaInput'
import { PasswordStrength } from '@/components/common/PasswordStrength'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail } from '@/utils/validate'
import { AuthCenter } from './AuthSplit'

type FormValues = {
  email: string
  password?: string
  confirmPassword?: string
  captcha_id: string
  captcha_value: string
}

export function ForgotPasswordPage() {
  const [form] = Form.useForm<FormValues>()
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef<CaptchaInputHandle>(null)
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const token = params.get('token') || ''
  const isResetMode = Boolean(token)
  const captchaId = Form.useWatch('captcha_id', form) || ''
  const captchaValue = Form.useWatch('captcha_value', form) || ''
  const password = Form.useWatch('password', form) || ''

  async function sendLink() {
    try {
      await form.validateFields(['email', 'captcha_value'])
    } catch {
      return
    }
    const values = form.getFieldsValue()
    if (!isValidEmail(values.email || '')) {
      message.warning('请输入有效邮箱')
      return
    }
    setLoading(true)
    try {
      await authApi.forgotPassword({
        email: values.email.trim(),
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('密码重置链接已发送')
      await captchaRef.current?.refresh()
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  async function resetPassword() {
    try {
      await form.validateFields()
    } catch {
      return
    }
    const values = form.getFieldsValue()
    if (!isValidEmail(values.email || '')) {
      message.warning('请输入有效邮箱')
      return
    }

    setLoading(true)
    try {
      const encrypted = await encryptPasswords({ password: values.password || '' })
      await authApi.resetPassword({
        email: values.email.trim(),
        token,
        password: encrypted.values.password || '',
        password_key_id: encrypted.password_key_id,
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('密码已重置，请重新登录')
      navigate('/auth/login')
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthCenter
      title={isResetMode ? '重置密码' : '找回密码'}
      description={
        isResetMode
          ? '请设置新密码。重置链接在过期前仅可使用一次。'
          : '请输入已启用登录的邮箱，系统将发送密码重置链接。'
      }
    >
      <ConfigProvider componentSize="large">
        <Form
          form={form}
          layout="vertical"
          requiredMark={false}
          initialValues={{ captcha_id: '', captcha_value: '' }}
          onFinish={() => {
            void (isResetMode ? resetPassword() : sendLink())
          }}
        >
          <Form.Item name="email" rules={[{ required: true, message: '请输入登录邮箱' }]}>
            <Input placeholder="登录邮箱" allowClear />
          </Form.Item>

          {isResetMode ? (
            <>
              <Form.Item name="password" rules={[{ required: true, message: '请输入新密码' }]}>
                <Input.Password placeholder="新密码（至少 8 位，含大小写、数字与特殊字符）" />
              </Form.Item>
              <PasswordStrength password={password} />
              <Form.Item
                name="confirmPassword"
                dependencies={['password']}
                rules={[
                  { required: true, message: '请确认密码' },
                  ({ getFieldValue }) => ({
                    validator(_, value) {
                      if (!value || getFieldValue('password') === value) {
                        return Promise.resolve()
                      }
                      return Promise.reject(new Error('两次输入的密码不一致'))
                    },
                  }),
                ]}
              >
                <Input.Password placeholder="确认新密码" />
              </Form.Item>
            </>
          ) : null}

          <Form.Item name="captcha_id" hidden>
            <Input />
          </Form.Item>

          <Form.Item name="captcha_value" rules={[{ required: true, message: '请输入验证码' }]}>
            <CaptchaInput
              ref={captchaRef}
              size="large"
              captchaId={captchaId}
              captchaValue={captchaValue}
              onCaptchaIdChange={(v) => form.setFieldValue('captcha_id', v)}
              onCaptchaValueChange={(v) => form.setFieldValue('captcha_value', v)}
            />
          </Form.Item>

          <Form.Item>
            <Button type="primary" htmlType="submit" block loading={loading}>
              {isResetMode ? '重置密码' : '发送重置链接'}
            </Button>
          </Form.Item>

          <div className="auth-center__links">
            <Link to="/auth/login">返回登录</Link>
            {isResetMode ? (
              <Button type="link" className="!px-0" onClick={() => void sendLink()}>
                发送新链接
              </Button>
            ) : (
              <Link to="/auth/register">去注册</Link>
            )}
          </div>
        </Form>
      </ConfigProvider>
    </AuthCenter>
  )
}
