// web/portal/src/pages/auth/register.tsx
import { useRef, useState } from 'react'
import { Button, Form, Input, message } from 'antd'
import { Link, useNavigate } from 'react-router-dom'
import * as authApi from '@/api/auth'
import { CaptchaInput, type CaptchaInputHandle } from '@/components/common/CaptchaInput'
import { encryptPasswords } from '@/utils/security'
import { isValidEmail } from '@/utils/validate'
import { AuthSplit } from './AuthSplit'

type FormValues = {
  account: string
  nickname: string
  email: string
  password: string
  confirmPassword: string
  captcha_id: string
  captcha_value: string
}

export function RegisterPage() {
  const [form] = Form.useForm<FormValues>()
  const [loading, setLoading] = useState(false)
  const captchaRef = useRef<CaptchaInputHandle>(null)
  const navigate = useNavigate()
  const captchaId = Form.useWatch('captcha_id', form) || ''
  const captchaValue = Form.useWatch('captcha_value', form) || ''

  async function onFinish(values: FormValues) {
    const account = values.account.trim()
    const nickname = values.nickname.trim()
    const email = values.email.trim()

    if (account.length < 3 || account.length > 64) {
      message.warning('用户名需 3-64 个字符')
      return
    }
    if (!nickname || nickname.length > 64) {
      message.warning('昵称为必填项')
      return
    }
    if (!isValidEmail(email) || email.length > 128) {
      message.warning('邮箱格式不正确')
      return
    }

    setLoading(true)
    try {
      const encrypted = await encryptPasswords({ password: values.password })
      await authApi.register({
        account,
        email,
        nickname,
        password: encrypted.values.password || '',
        password_key_id: encrypted.password_key_id,
        captcha_id: values.captcha_id,
        captcha_value: values.captcha_value,
      })
      message.success('注册成功，请登录')
      navigate('/auth/login')
    } catch {
      await captchaRef.current?.refresh()
    } finally {
      setLoading(false)
    }
  }

  return (
    <AuthSplit title="注册" subtitle="创建门户账号，开始刷题与参赛。">
      <Form
        form={form}
        layout="vertical"
        initialValues={{ captcha_id: '', captcha_value: '' }}
        onFinish={onFinish}
      >
        <Form.Item
          name="account"
          label="用户名"
          rules={[
            { required: true, message: '请输入用户名' },
            { min: 3, max: 64, message: '用户名需 3-64 个字符' },
          ]}
        >
          <Input placeholder="输入用户名" allowClear />
        </Form.Item>

        <Form.Item
          name="nickname"
          label="昵称"
          rules={[
            { required: true, message: '请输入昵称' },
            { max: 64, message: '昵称最多 64 个字符' },
          ]}
        >
          <Input placeholder="输入昵称" allowClear />
        </Form.Item>

        <Form.Item
          name="email"
          label="邮箱"
          rules={[
            { required: true, message: '请输入邮箱' },
            { type: 'email', message: '邮箱格式不正确' },
            { max: 128, message: '邮箱最多 128 个字符' },
          ]}
        >
          <Input placeholder="your@example.com" allowClear />
        </Form.Item>

        <Form.Item
          name="password"
          label="密码"
          rules={[
            { required: true, message: '请输入密码' },
            { min: 6, message: '密码至少 6 个字符' },
          ]}
        >
          <Input.Password placeholder="至少 6 个字符" />
        </Form.Item>

        <Form.Item
          name="confirmPassword"
          label="确认密码"
          dependencies={['password']}
          rules={[
            { required: true, message: '请确认密码' },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue('password') === value) {
                  return Promise.resolve()
                }
                return Promise.reject(new Error('两次密码输入不一致'))
              },
            }),
          ]}
        >
          <Input.Password placeholder="再次输入密码" />
        </Form.Item>

        <Form.Item name="captcha_id" hidden>
          <Input />
        </Form.Item>

        <Form.Item
          name="captcha_value"
          label="验证码"
          rules={[{ required: true, message: '请输入验证码' }]}
        >
          <CaptchaInput
            ref={captchaRef}
            captchaId={captchaId}
            captchaValue={captchaValue}
            onCaptchaIdChange={(v) => form.setFieldValue('captcha_id', v)}
            onCaptchaValueChange={(v) => form.setFieldValue('captcha_value', v)}
          />
        </Form.Item>

        <Form.Item>
          <Button type="primary" htmlType="submit" block loading={loading}>
            注册
          </Button>
        </Form.Item>
      </Form>

      <div className="text-center text-gray-500">
        已有账号？ <Link to="/auth/login">立即登录</Link>
      </div>
    </AuthSplit>
  )
}

// web/portal-nuxt/app/pages/auth/register.vue
<script setup lang="ts">
const router = useRouter()
const toast = useToast()
const { register } = useAuth()
const captcha = useCaptcha()
const loading = ref(false)

const formState = reactive({
  username: '',
  nickname: '',
  email: '',
  password: '',
  confirmPassword: '',
})

onMounted(() => {
  captcha.refresh()
})

async function onSubmit() {
  const { username, nickname, email, password, confirmPassword } = formState

  if (!username || username.length < 3 || username.length > 64) {
    toast.add({ title: '错误', description: '用户名需 3-64 个字符', color: 'error' })
    return
  }
  if (!nickname || nickname.length > 64) {
    toast.add({ title: '错误', description: '昵称为必填项', color: 'error' })
    return
  }
  if (!email || !/\S+@\S+\.\S+/.test(email) || email.length > 128) {
    toast.add({ title: '错误', description: '邮箱格式不正确', color: 'error' })
    return
  }
  if (!password || password.length < 6) {
    toast.add({ title: '错误', description: '密码至少 6 个字符', color: 'error' })
    return
  }
  if (password !== confirmPassword) {
    toast.add({ title: '错误', description: '两次密码输入不一致', color: 'error' })
    return
  }
  if (!captcha.captchaValue.value?.trim()) {
    toast.add({ title: '错误', description: '请输入验证码', color: 'error' })
    return
  }

  loading.value = true
  try {
    await register(
      username,
      email,
      password,
      nickname,
      captcha.captchaId.value,
      captcha.captchaValue.value.trim(),
    )
    toast.add({ title: '注册成功，请登录', color: 'success' })
    router.push('/auth/login')
  } catch {
    captcha.refresh()
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="flex min-h-dvh items-center justify-center p-4">
    <UCard class="w-full max-w-md">
      <template #header>
        <div class="flex items-center gap-3">
          <div
            class="flex size-10 items-center justify-center rounded-full bg-primary/10 text-primary"
          >
            <UIcon name="i-lucide-user-plus" class="size-5" />
          </div>
          <div>
            <h2 class="text-lg font-semibold">创建账号</h2>
            <p class="text-sm text-muted">注册一个新账号</p>
          </div>
        </div>
      </template>

      <UForm :state="formState" @submit="onSubmit">
        <UFormField label="用户名" name="username" required>
          <UInput v-model="formState.username" placeholder="输入用户名" class="w-full" />
        </UFormField>

        <UFormField label="昵称" name="nickname" required>
          <UInput v-model="formState.nickname" placeholder="输入昵称" class="w-full" />
        </UFormField>

        <UFormField label="邮箱" name="email" required>
          <UInput
            v-model="formState.email"
            type="email"
            placeholder="your@example.com"
            class="w-full"
          />
        </UFormField>

        <UFormField label="密码" name="password" required>
          <UInput
            v-model="formState.password"
            type="password"
            placeholder="至少 6 个字符"
            class="w-full"
          />
          <PasswordStrengthBar :password="formState.password" />
        </UFormField>

        <UFormField label="确认密码" name="confirmPassword" required>
          <UInput
            v-model="formState.confirmPassword"
            type="password"
            placeholder="再次输入密码"
            class="w-full"
          />
        </UFormField>

        <UFormField label="验证码" required>
          <div class="flex gap-2 w-full items-stretch">
            <UInput v-model="captcha.captchaValue.value" placeholder="输入验证码" class="flex-1" />
            <div
              class="w-24 flex-shrink-0 cursor-pointer rounded overflow-hidden bg-muted"
              @click="captcha.refresh()"
            >
              <img
                v-if="captcha.captchaImage.value"
                :src="captcha.captchaImage.value"
                alt="验证码"
                class="h-full w-full object-contain"
              />
              <div v-else class="flex items-center justify-center h-full text-xs text-muted">
                点击获取
              </div>
            </div>
          </div>
        </UFormField>

        <UButton type="submit" color="primary" size="lg" block :loading="loading" class="mt-6">
          注册
        </UButton>
      </UForm>

      <template #footer>
        <p class="text-center text-sm text-muted">
          已有账号？
          <NuxtLink to="/auth/login" class="text-primary font-medium">立即登录</NuxtLink>
        </p>
      </template>
    </UCard>
  </div>
</template>
