// web/portal/src/components/oj/ContestStatusBadge.tsx
import { Tag } from 'antd'

const statusMeta: Record<string, { color: string; label: string }> = {
  SCHEDULED: { color: 'blue', label: '未开始' },
  RUNNING: { color: 'green', label: '进行中' },
  ENDED: { color: 'default', label: '已结束' },
  LOCKED: { color: 'orange', label: '已锁定' },
}

type Props = {
  status?: string | null
}

export function ContestStatusBadge({ status }: Props) {
  const meta = statusMeta[status ?? ''] ?? { color: 'default', label: status || '-' }
  return <Tag color={meta.color}>{meta.label}</Tag>
}

// web/portal-nuxt/app/components/oj/ContestStatusBadge.vue
<script setup lang="ts">
const props = defineProps<{ status: string }>()

const meta = computed(() => {
  switch (props.status) {
    case 'SCHEDULED':
      return { label: '未开始', color: 'neutral' as const }
    case 'RUNNING':
      return { label: '进行中', color: 'success' as const }
    case 'ENDED':
      return { label: '已结束', color: 'warning' as const }
    case 'LOCKED':
      return { label: '已锁定', color: 'error' as const }
    default:
      return { label: props.status, color: 'neutral' as const }
  }
})
</script>

<template>
  <UBadge :color="meta.color" variant="subtle">
    {{ meta.label }}
  </UBadge>
</template>
